-- ── Bibliothèque d'ouvrages : référentiels et articles ───────────────────────
-- La page « Cahier des charges » devient la bibliothèque des articles
-- réutilisables dans les CCTP, DPGF et DQE. Cette migration pose les trois
-- référentiels sur lesquels un article se classe, étend `articles_type` pour
-- les porter, et ouvre l'historique de prix.
--
-- Les tables `ref_*` sont GLOBALES, pas multi-tenant : ce sont des
-- nomenclatures publiques (EU SfB plus, NF DTU/BNTEC, NAF INSEE), identiques
-- pour tous les cabinets. Elles portent tout de même une RLS en lecture seule
-- pour les utilisateurs authentifiés — le backend écrit avec la service role,
-- qui la contourne. Les dupliquer par tenant n'apporterait rien et
-- multiplierait par le nombre de cabinets une donnée qui ne change qu'à
-- chaque révision de la norme.
--
-- Sources exactes des données injectées plus bas :
--   - EU SfB plus, août 2024 (classification des éléments d'ouvrage)
--   - NF DTU pour les métiers du Bâtiment, BNTEC/FFB, janvier 2026
--   - Nomenclature d'activités française NAF rév. 2, INSEE (section F et
--     activités connexes du bâtiment)

-- ── Référentiel 1 : éléments d'ouvrage (EU SfB plus) ────────────────────────
CREATE TABLE IF NOT EXISTS ref_sfb_elements (
  code        TEXT PRIMARY KEY,
  parent_code TEXT REFERENCES ref_sfb_elements(code) ON DELETE CASCADE,
  niveau      SMALLINT NOT NULL CHECK (niveau IN (1, 2)),
  libelle     TEXT NOT NULL,
  libelle_en  TEXT,
  position    INT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_ref_sfb_parent ON ref_sfb_elements(parent_code);

-- ── Référentiel 2 : corps d'état (nomenclature FFB) et NF DTU ───────────────
CREATE TABLE IF NOT EXISTS ref_corps_etat (
  code     TEXT PRIMARY KEY,
  famille  TEXT NOT NULL,
  libelle  TEXT NOT NULL,
  position INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ref_dtu (
  code       TEXT PRIMARY KEY,          -- « NF DTU 13.1 »
  prefixe    TEXT NOT NULL,             -- NF DTU | XP DTU | FD DTU
  numero     TEXT NOT NULL,             -- « 13.1 »
  titre      TEXT NOT NULL,
  norme      TEXT,                      -- référence AFNOR, « P11-201 »
  amendement BOOLEAN NOT NULL DEFAULT FALSE
);

-- Un même DTU relève parfois de deux métiers (NF DTU 26.1 : façades ET
-- enduits intérieurs), d'où une liaison N-N plutôt qu'une colonne.
CREATE TABLE IF NOT EXISTS ref_dtu_corps_etat (
  dtu_code        TEXT NOT NULL REFERENCES ref_dtu(code) ON DELETE CASCADE,
  corps_etat_code TEXT NOT NULL REFERENCES ref_corps_etat(code) ON DELETE CASCADE,
  PRIMARY KEY (dtu_code, corps_etat_code)
);
CREATE INDEX IF NOT EXISTS idx_ref_dtu_corps_etat_corps ON ref_dtu_corps_etat(corps_etat_code);

-- ── Référentiel 3 : codes NAF (INSEE) ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS ref_naf (
  code        TEXT PRIMARY KEY,
  parent_code TEXT,
  niveau      SMALLINT NOT NULL,   -- 2 division, 3 groupe, 4 classe, 5 sous-classe
  libelle     TEXT NOT NULL,
  section     TEXT
);
CREATE INDEX IF NOT EXISTS idx_ref_naf_parent ON ref_naf(parent_code);

-- Lecture ouverte à tout utilisateur authentifié, écriture réservée à la
-- service role (qui contourne la RLS) : une nomenclature ne se modifie pas
-- depuis l'application.
ALTER TABLE ref_sfb_elements   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ref_corps_etat     ENABLE ROW LEVEL SECURITY;
ALTER TABLE ref_dtu            ENABLE ROW LEVEL SECURITY;
ALTER TABLE ref_dtu_corps_etat ENABLE ROW LEVEL SECURITY;
ALTER TABLE ref_naf            ENABLE ROW LEVEL SECURITY;
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['ref_sfb_elements', 'ref_corps_etat', 'ref_dtu',
                           'ref_dtu_corps_etat', 'ref_naf'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS "read_all_authenticated" ON %I', t);
    EXECUTE format('CREATE POLICY "read_all_authenticated" ON %I FOR SELECT USING (auth.role() = ''authenticated'')', t);
  END LOOP;
END;
$$;

-- ── Articles : classement, provenance, traçabilité ──────────────────────────
-- `articles_type` portait déjà designation/unite/prix_unitaire/categorie/
-- lot_type (migrate_add_bpu.sql). S'y ajoutent le classement sur les trois
-- référentiels et la provenance.
ALTER TABLE articles_type ADD COLUMN IF NOT EXISTS sfb_code        TEXT REFERENCES ref_sfb_elements(code) ON DELETE SET NULL;
ALTER TABLE articles_type ADD COLUMN IF NOT EXISTS dtu_code        TEXT REFERENCES ref_dtu(code)          ON DELETE SET NULL;
ALTER TABLE articles_type ADD COLUMN IF NOT EXISTS corps_etat_code TEXT REFERENCES ref_corps_etat(code)   ON DELETE SET NULL;
ALTER TABLE articles_type ADD COLUMN IF NOT EXISTS naf_code        TEXT REFERENCES ref_naf(code)          ON DELETE SET NULL;

-- `origine` est le repère demandé : il distingue un article du fonds de
-- référence d'un article créé par le cabinet, et sert à le signaler comme tel
-- dans les CCTP et DPGF. `source` (déjà là) garde le détail libre
-- (« projet:<id> »), cette colonne-ci porte le vocabulaire fermé.
ALTER TABLE articles_type ADD COLUMN IF NOT EXISTS origine TEXT NOT NULL DEFAULT 'saisie';
ALTER TABLE articles_type DROP CONSTRAINT IF EXISTS articles_type_origine_check;
ALTER TABLE articles_type ADD CONSTRAINT articles_type_origine_check
  CHECK (origine IN ('reference', 'saisie', 'bpu', 'offre', 'import'));

ALTER TABLE articles_type ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE articles_type ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE articles_type ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_articles_type_sfb        ON articles_type(tenant_id, sfb_code);
CREATE INDEX IF NOT EXISTS idx_articles_type_dtu        ON articles_type(tenant_id, dtu_code);
CREATE INDEX IF NOT EXISTS idx_articles_type_corps_etat ON articles_type(tenant_id, corps_etat_code);
CREATE INDEX IF NOT EXISTS idx_articles_type_origine    ON articles_type(tenant_id, origine);

-- ── Historique de prix ──────────────────────────────────────────────────────
-- `articles_type.prix_unitaire` reste le prix courant, celui qu'on injecte
-- dans un DPGF. Cette table garde chaque prix OBSERVÉ, sans l'écraser : c'est
-- elle qui permettra d'enrichir la bibliothèque avec les réponses des
-- entreprises aux appels d'offres et de lire une fourchette plutôt qu'un
-- chiffre unique.
CREATE TABLE IF NOT EXISTS article_prix_observations (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  article_id       TEXT NOT NULL REFERENCES articles_type(id) ON DELETE CASCADE,
  prix_ht          NUMERIC NOT NULL,
  unite            TEXT,
  date_observation DATE NOT NULL DEFAULT CURRENT_DATE,
  origine          TEXT NOT NULL DEFAULT 'saisie'
                   CHECK (origine IN ('saisie', 'bpu', 'offre', 'marche', 'import')),
  entreprise       TEXT,     -- l'entreprise dont émane le prix, pour une offre
  project_id       TEXT,
  tender_id        TEXT,
  notes            TEXT,
  created_by       TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_prix_obs_article ON article_prix_observations(tenant_id, article_id, date_observation DESC);
CREATE INDEX IF NOT EXISTS idx_prix_obs_tenant  ON article_prix_observations(tenant_id);

ALTER TABLE article_prix_observations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tenant_isolation" ON article_prix_observations;
CREATE POLICY "tenant_isolation" ON article_prix_observations
  FOR ALL USING (tenant_id = my_tenant_id());

-- Synchronisation cloud <-> local, comme migrate_add_bpu.sql l'a fait pour
-- bpu_data. server/syncTables.ts doit lister 'article_prix_observations' en
-- regard, et le littéral ARRAY[...] de migrate_add_sync_infra.sql aussi.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'touch_updated_at') THEN
    EXECUTE 'DROP TRIGGER IF EXISTS trg_touch_updated_at ON articles_type';
    EXECUTE 'CREATE TRIGGER trg_touch_updated_at BEFORE UPDATE ON articles_type '
         || 'FOR EACH ROW EXECUTE FUNCTION touch_updated_at()';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'log_sync_change') THEN
    EXECUTE 'DROP TRIGGER IF EXISTS trg_log_sync_change ON article_prix_observations';
    EXECUTE 'CREATE TRIGGER trg_log_sync_change AFTER INSERT OR UPDATE OR DELETE ON article_prix_observations '
         || 'FOR EACH ROW EXECUTE FUNCTION log_sync_change()';
  END IF;
END;
$$;


-- ── Données de référence ────────────────────────────────────────────────────
-- EU SfB plus (août 2024) : 32 éléments, 284 sous-éléments.
INSERT INTO ref_sfb_elements (code, parent_code, niveau, libelle, libelle_en, position) VALUES
  ('13', NULL, 1, 'COUCHES SUR SOL, PLANCHERS SUR SOL', 'FLOOR BEDS', 0),
  ('13/0', '13', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 1),
  ('13/1', '13', 2, 'Infrastructure: ex. compactage de couches existantes, nivellement de couches existantes, sable stabilisé, couche de pierre concassée,...', 'Infrastructure: e.g. compaction of existing layers, leveling of existing layers, stabilized sand, layer of crushed stone,...', 2),
  ('13/2', '13', 2, 'Couche sur sol: ex. sol en béton,...', 'Floor on grade: e.g. concrete floor,...', 3),
  ('13/3', '13', 2, 'Poutres pour couche sur sol: par ex. nervures de raidissement pour couche sur sol,...', 'Beams for floor bed: e.g. stiffening ribs for floor on grade,...', 4),
  ('13/4', '13', 2, 'Traitement: ex. nivelage du béton,...', 'Treatment: e.g. leveling of concrete,...', 5),
  ('13/5', '13', 2, 'Installation pour fluides: ex. drainage de la couche au sol,...', 'Installations fluids: e.g. drainage for the layer on the ground,...', 6),
  ('13/6', '13', 2, 'Installations électriques: ex. câbles à résistance électrique intégrés pendant la construction', 'Electrical installations: e.g. electrical resistance heating ducts incorporated during construction', 7),
  ('13/7', '13', 2, 'Sous-éléments ajoutés pour la protection ou l''embellissement de la partie principale', 'Sub-elements added for protection or embellishment to the primary part', 8),
  ('13/8', '13', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 9),
  ('16', NULL, 1, 'FONDATIONS, MURS DE SOUTENEMENT', 'FOUNDATIONS, RETAINING WALLS', 10),
  ('16/0', '16', 2, 'Démolition, excavations: Résultat des travaux de démolition ou d'' excavations spécifiques à cet élément', 'Demolition, excavations: Result of demolition works or excavations specific to this element', 11),
  ('16/1', '16', 2, 'Infrastructure: ex. compactage de couches existantes, nivellement de couches existantes, couche de béton ,...', 'Infrastructure: e.g. compaction of existing layers, leveling of existing layers, basic concrete layer,...', 12),
  ('16/2', '16', 2, 'Mur de fondation', 'Foundation wall', 13),
  ('16/3', '16', 2, 'Semelle de fondation: S''il n''y a pas de différence entre la semelle et le mur ou si cela n''est pas pertinent, utilisez le code (16/2)', 'Foutings, strip founations: If there is no difference between sole and wall or this is not relevant, use code (16/2)', 14),
  ('16/4', '16', 2, 'Finition', 'Finishing', 15),
  ('16/5', '16', 2, 'Installations contenant des fluides: ex. drainage pour fondation,...', 'Installations fluids: e.g. drainage for foundation,...', 16),
  ('16/6', '16', 2, 'Installations électriques: ex. prise de terre (intégrée à la fondation),...', 'Electrical installations: e.g. earth loop (integrated in foundation),...', 17),
  ('16/7', '16', 2, 'Remblais: Résultat des remblais à la fondation, specifique au mur de soutènement', 'Backfills: Result of earth fills specific for foundation, retaining wall', 18),
  ('16/8', '16', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 19),
  ('17', NULL, 1, 'FONDATIONS SUR PIEUX', 'PILE FOUNDATIONS', 20),
  ('17/0', '17', 2, 'Démolition, Excavations : Résultat des travaux de démolition ou de fouilles spécifiques aux fondations sur pieux', 'Demolition, Excavations: Result of demolition works or excavations specific to piled foundations', 21),
  ('17/2', '17', 2, 'Poutres de liaison, têtes de pieux', 'Connecting beams, pile head', 22),
  ('17/3', '17', 2, 'Pieux de fondation', 'Foundation piles', 23),
  ('17/7', '17', 2, 'Remblais: Résultat des remblais spécifiques pour les fondations sur pieux', 'Backfills: Result of earth fills specific for pile foundations', 24),
  ('17/8', '17', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 25),
  ('21', NULL, 1, 'MURS EXTERIEURS', 'EXTERNAL WALLS', 26),
  ('21/0', '21', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 27),
  ('21/1', '21', 2, 'Infrastructure: ex. renforcement d''autres éléments,...', 'Infrastructure: e.g. reinforcement of other elements, ...', 28),
  ('21/2', '21', 2, 'Mur: sous-élément qui remplit une fonction de séparation d''espace', 'Wall: Sub-element that performs space-separating function', 29),
  ('21/3', '21', 2, 'Poteaux et poutres: S''il n''y a pas de colonnes ou de poutres dans le mur, utilisez le code (21/2).', 'Columns and beams: If there are no columns or beams in the wall, use code (21/2).', 30),
  ('21/4', '21', 2, 'Finition: ex. couche protectrice sur bois, sur fer,...', 'Finishing: e.g. protective layer on wood, on iron,...', 31),
  ('21/5', '21', 2, 'Approvisionnement en liquide incorporé lors de la construction de l''élément primaire,...', 'Installations fluids: e.g. heating pipes incorporated during the construction of the primary element,...', 32),
  ('21/6', '21', 2, 'Installations électriques: ex. câbles électriques incorporés dans l''élément préfabriqué,...', 'Electrical installations: e.g. electricity cables incorporated in prefab element,...', 33),
  ('21/7', '21', 2, 'Sous-élément ajouté pour la protection ou l''embellissement de la partie principale, lorsqu''il ne nécessite pas de finition', 'Sub-element added for protection or embellishment to primary part, when not requiring finishing', 34),
  ('21/8', '21', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 35),
  ('22', NULL, 1, 'MURS INTERIEURES', 'INTERNAL WALLS, PARTITIONS', 36),
  ('22/0', '22', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 37),
  ('22/1', '22', 2, 'Infrastructure: ex. poutre inversée spécifique pour mur,...', 'Infrastructure: e.g. upside-down beam specifically for wall,...', 38),
  ('22/2', '22', 2, 'Mur: sous-élément qui remplit une fonction de séparation d''espace', 'Wall: Sub-element that performs space-separating function', 39),
  ('22/3', '22', 2, 'Poteaux et poutres', 'Columns and beams', 40),
  ('22/4', '22', 2, 'Finition: ex. couche de protection sur colonnes et poutres métalliques, sur ossature bois dans un mur de remplissage,...', 'Finishing: e.g. protective layer on metal columns and beams, on wooden frame of infill wall,...', 41),
  ('22/5', '22', 2, 'Installations contenant des fluides: ex. tuyaux de chauffage incorporés lors de la construction de l''élément primaire,...', 'Installations fluids: e.g. heating pipes incorporated during the construction of the primary element,...', 42),
  ('22/6', '22', 2, 'Installations électriques: ex. câbles électriques incorporés lors de la préfabrication,...', 'Electrical installations: e.g. electrical cables incorporated during prefabrication,...', 43),
  ('22/7', '22', 2, 'Sous-éléments ajoutés pour la protection ou l''embellissement de la partie principale, lorsqu''elle ne nécessite pas de finition.', 'Sub-elements added for protection or embellishment to the primary part, when it does not require finishing.', 44),
  ('22/8', '22', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 45),
  ('23', NULL, 1, 'PLANCHERS', 'FLOORS', 46),
  ('23/0', '23', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 47),
  ('23/1', '23', 2, 'Infrastructure: ex. renforcement des éléments sur lesquels repose le plancher,...', 'Infrastructure: e.g. reinforcement of elements on which floor is placed ,...', 48),
  ('23/2', '23', 2, 'Dalle de plancher : Sous-élément qui remplit une fonction de séparation d''espace', 'Floor plate: Sub-element that fulfills a space-separating function', 49),
  ('23/3', '23', 2, 'Poutres de plancher: Sous-élément qui transfère les charges de la dalle de plancher (23/2) à la structure porteuse (21), (22), (28).', 'Floor beams: Sub-member that transfers the loads from the floor slab (23/2) to the supporting structure (21), (22), (28).', 50),
  ('23/4', '23', 2, 'Finition: ex. traitement anti-pourriture d''un plancher en bois, traitement anti-rouille, ...', 'Finishing: e.g. anti-rot treatment wooden floor, anti-rust treatment ,...', 51),
  ('23/5', '23', 2, 'Alimentation en liquides incorporée au plancher incorporés lors de la construction de l''élément primaire,...', 'Liquids supply services incorporated in floor incorporated during the construction of the primary element,...', 52),
  ('23/6', '23', 2, 'Installations électriques: ex. résistances électriques incorporées dans l''élément primaire du plancher,...', 'Electrical installations: e.g. electrical resistances incorporated in primary floor element,...', 53),
  ('23/7', '23', 2, 'Sous-éléments ajoutés pour la protection ou l''embellissement de la partie principale, lorsqu''elle ne nécessite pas de finition', 'Sub-elements added for protection or embellishment to the primary part, when it does not require finishing', 54),
  ('23/8', '23', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 55),
  ('24', NULL, 1, 'ESCALIERS, PLANS INCLINES', 'STAIRS, RAMPS', 56),
  ('24/0', '24', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 57),
  ('24/1', '24', 2, 'Infrastructure: ex. renforcement d''autres éléments, ancrage dans d''autres éléments,...', 'Infrastructure: e.g. reinforcement of other elements, anchoring in other elements,...', 58),
  ('24/2', '24', 2, 'Marches, paliers', 'Steps, platforms', 59),
  ('24/3', '24', 2, 'Limons d''escalier: ex. limon central d''escalier, mur de support spécial pour escaliers,...', 'Stair stringers: e.g. central stair stringer, special support wall for stairs,...', 60),
  ('24/4', '24', 2, 'Finition', 'Finishing', 61),
  ('24/5', '24', 2, 'Installations contenant des fluides (incorporées)', 'Fluid installations (incorporated)', 62),
  ('24/6', '24', 2, 'Installations électriques (incorporées)', 'Electrical installations (incorporated)', 63),
  ('24/7', '24', 2, 'Sous-éléments ajoutés pour pour la protection ou l''embellissement de la partie principale, lorsqu''elle ne nécessite pas de finition', 'Sub-elements added to protect or embellish the primary part, when it does not require finishing', 64),
  ('24/8', '24', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 65),
  ('27', NULL, 1, 'TOITURES', 'ROOFS', 66),
  ('27/0', '27', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 67),
  ('27/1', '27', 2, 'Infrastructure: ex. ancrages encastrés dans les murs, ...', 'Infrastructure: e.g. anchors cast into walls, ...', 68),
  ('27/2', '27', 2, 'Dalle de toiture : Sous-élément avec fonction de separation des espaces', 'Roof plate: Sub-element with space-delimiting function', 69),
  ('27/3', '27', 2, 'Structure de support : Sous-élément qui transfère les charges de la dalle de toit (27/2) vers d''autres éléments (21), (22) ou (28)', 'Support structure: Sub-element that transfers the loads from the roof slab (27/2) to other elements (21), (22) or (28)', 70),
  ('27/4', '27', 2, 'Finition: ex. traitement anti-pourriture des charpentes, traitement antirouille des poutres en acier,...', 'Finishing: e.g. anti-rot treatment of wooden roofstructute, anti-rust treatment of steel beams,...', 71),
  ('27/5', '27', 2, 'Installations contenant des fluides (incorporées)', 'Fluid installations (incorporated)', 72),
  ('27/6', '27', 2, 'Installations électriques (incorporées)', 'Electrical installations (incorporated)', 73),
  ('27/7', '27', 2, 'Sous-éléments ajoutés pour pour la protection ou l''embellissement de la partie principale, lorsqu''elle ne nécessite pas de finition', 'Sub-elements added to protect or enhance the primary part, when it does not require finishing', 74),
  ('27/8', '27', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 75),
  ('28', NULL, 1, 'OSSATURES, ELEMENTS DE (2-) NON DECRITS Cl- DESSUS', 'BUILDING FRAMES, OTHER ELEMENTS OF (2-)', 76),
  ('28/0', '28', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 77),
  ('28/1', '28', 2, 'Infrastructure: ex. renforts à l''emplacement d''une colonne, ...', 'Infrastructure: e.g. reinforcements at the location of the column, ...', 78),
  ('28/2', '28', 2, 'Colonnes: colonnes non incorporées (les colonnes incorporées dans les murs sont incluses dans ces murs)', 'Columns: Freestanding columns (columns incorporated into walls are included in those walls)', 79),
  ('28/3', '28', 2, 'Poutres : Poutres qui transfèrent les charges aux colonnes non incorporées dans les murs, planchrs ou toitures', 'Beams who transfer the load to free-standing columns, i.e. not incorporated in walls, floors or roofs', 80),
  ('28/4', '28', 2, 'Traitement, finition: ex. couche de protection, couche de peinture sur colonnes et poutres en bois, acier,...', 'Treatment, Finishing: e.g. anti-rot treatment of wooden beams, anti rust tratement of steel beams,...', 81),
  ('28/5', '28', 2, 'Installations contenant des fluides (incorporées)', 'Fluid installations (incorporated)', 82),
  ('28/6', '28', 2, 'Installations électriques (incorporées)', 'Electrical installations (incorporated)', 83),
  ('28/7', '28', 2, 'Fixation ajoutée : Sous-éléments ajoutés pourpour la protection ou l''embellissement de la partie principale, lorsqu''elle ne nécessite pas de finition', 'Sub-elements added to protect or embellish the primary part, when this does not require a finish', 84),
  ('28/8', '28', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 85),
  ('31', NULL, 1, 'ELEMENTS SECONDAIRES DES MURS EXTERIEURS', 'SECONDARY ELEMENTS TO EXTERNAL WALLS', 86),
  ('31/0', '31', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 87),
  ('31/1', '31', 2, 'Infrastructure: ex. Linteau', 'Infrastructure: e.g. lintel', 88),
  ('31/2', '31', 2, 'Pièces de remplissag: ex. vitrage', 'Closing parts: e.g. glazing', 89),
  ('31/3', '31', 2, 'Chassis y compris charnières et serrures', 'Frame including hinges and locks', 90),
  ('31/4', '31', 2, 'Traitement, finition: ex. couche de peinture, couche de protection du bois', 'Treatment, finishing: e.g. paint layer, wood protection layer', 91),
  ('31/5', '31', 2, 'Installations contenant des fluides (incorporées)', 'Fluids installations (incorporated)', 92),
  ('31/6', '31', 2, 'Installations électriques (incorporées): ex. installation électrique pour déverrouiller les portes, mécanisme de fermeture électrique pour portes coupe-feu,...', 'Electrical installations (incorporated): e.g. electrical installation to unlock doors, electrical closing mechanism for fire doors, ...', 93),
  ('31/7', '31', 2, 'Sous-éléments ajoutés: ex. pour assombrissement, protection solaire ou blindage', 'Added Sub-elements: e.g. for darkening, sun protection or screening', 94),
  ('31/8', '31', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 95),
  ('32', NULL, 1, 'ELEMENTS SECONDAIRES DES MURS INTERIEURS', 'SECONDARY ELEMENTS TO INTERNAL WALLS', 96),
  ('32/0', '32', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 97),
  ('32/1', '32', 2, 'Infrastructure: ex. linteau,...', 'Infrastructure: e.g. lintel,...', 98),
  ('32/2', '32', 2, 'Pièces de remplissage: ex. vitrage', 'Closing parts: e.g. glazing', 99),
  ('32/3', '32', 2, 'Chassis y compris charnières et serrures', 'Frame including hinges and locks', 100),
  ('32/4', '32', 2, 'Traitement, finition: ex. couche de peinture, couche de protection du bois', 'Treatment, finishing: e.g. paint layer, wood protection layer', 101),
  ('32/5', '32', 2, 'Installations contenant des fluides: ex. Ferme-porte hydraulique,...', 'Installations fluids: e.g. hydraulic door closer,...', 102),
  ('32/6', '32', 2, 'Installations électriques: ex. ouvre-porte électrique, ferme-porte électrique en cas d''incendie,...', 'Installations electrical: e.g. electrical installation to unlock doors, electrical closing mechanism for fire doors, ...', 103),
  ('32/7', '32', 2, 'Sous-éléments ajoutés: ex. pour assombrissement, protection ou blindage', 'Added Sub-elements: e.g. for darkening or screening', 104),
  ('32/8', '32', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 105),
  ('33', NULL, 1, 'ELEMENTS SECONDAIRES DES PLANCHERS', 'SECONDARY EL EMENTS TO FLOORS', 106),
  ('33/0', '33', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 107),
  ('33/1', '33', 2, 'Infrastructure: ex. renforcement du sol dans la zone d''ouverture, ...', 'Infrastructure: e.g. reinforcement of floor surrounding an opening, ...', 108),
  ('33/2', '33', 2, 'Pièces de remplissage: panneau de remplissage sans cadre, treillis', 'Closing parts: filler panel without frame, latticework', 109),
  ('33/3', '33', 2, 'Cadre y compris charnières et serrures', 'Frame including hinges and locks', 110),
  ('33/4', '33', 2, 'Traitement, finition: ex. couche de peinture, couche de protection du bois', 'Treatment, finishing: e.g. paint layer, wood protection layer', 111),
  ('33/5', '33', 2, 'Installations contenant des fluides: ex. commande hydraulique pour trappe de sol,...', 'Fluid installations: e.g. hydraulic control for floor hatch,...', 112),
  ('33/6', '33', 2, 'Installations électriques: ex. Commande électrique pour trappe de sol,...', 'Installations electrical: e.g. electric control for floor hatch,...', 113),
  ('33/7', '33', 2, 'Équipement ajouté: Équipement d''assombrissement ou de protection, qui est ajouté en plus des sous-éléments mentionnés ci-dessus', 'Additional equipment: Equipment for dimming or shielding, which is added in addition to the above-mentioned sub-elements', 114),
  ('33/8', '33', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 115),
  ('34', NULL, 1, 'ELEMENTS SECONDAIRES DES ESCALIERS, PLANS INCLINES', 'SECONDARY ELEMENTS TO STAIRS, RAMPS', 116),
  ('34/0', '34', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 117),
  ('34/1', '34', 2, 'Infrastructure: ex. renfort d''escalier (24) pour montage de la rampe, ...', 'Infrastructure: e.g. Reinforcement of stairs (24) for attaching handrails,...', 118),
  ('34/2', '34', 2, 'Pièces de remplissage: Sous-élément de la rampe d''escalier qui remplit la fonction réelle de délimitation de l''espace', 'Closing parts: Sub-element of the stair railing that fulfills the actual space-delimiting function', 119),
  ('34/3', '34', 2, 'Structure de support: ex. balustres principaux, poignée,...', 'Support structure: e.g. main balusters, handle,...', 120),
  ('34/4', '34', 2, 'Traitement, finition: ex. couche de peinture, couche de protection du bois', 'Treatment, finishing: e.g. paint layer, wood protection layer', 121),
  ('34/5', '34', 2, 'Installations contenant des fluides (incorporées)', 'Fluid installations (incorporated)', 122),
  ('34/6', '34', 2, 'Installations électriques (incorporées)', 'Electrical installations (incorporated)', 123),
  ('34/7', '34', 2, 'Équipement ajouté: Sous-éléments ajoutés pour protéger ou embellir les sous-éléments mentionnés ci-dessus', 'Additional equipment: Sub-elements added to protect or embellishment of the above-mentioned sub-elements', 124),
  ('34/8', '34', 2, 'Sous-éléments non décrits ci-dessous', NULL, 125),
  ('37', NULL, 1, 'ELEMENTS SECONDAIRES DES TOITURES', 'SECONDARY ELEMENTS TO ROOFS', 126),
  ('37/0', '37', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 127),
  ('37/1', '37', 2, 'Infrastructure: ex. renforcement des menuiseries aux bord de l''ouverture', 'Infrastructure: e.g. Reinforcing carpentry at edges of openings, ...', 128),
  ('37/2', '37', 2, 'Pièces de remplissage: ex. Vitrage', 'Closing parts: e.g. glazing', 129),
  ('37/3', '37', 2, 'Chassis y compris charnières et serrures', 'Frame including hinges and locks', 130),
  ('37/4', '37', 2, 'Traitement, finition: ex. couche de peinture, couche de protection du bois', 'Treatment, finishing: e.g. paint layer, wood protection layer', 131),
  ('37/5', '37', 2, 'Installations contenant des fluides (incorporées)', 'Fluids installations (incorporated)', 132),
  ('37/6', '37', 2, 'Installations électriques: ex. commande d''ouverture électrique,...', 'Installations electrical: e.g. electric control to open, ...', 133),
  ('37/7', '37', 2, 'Équipement ajouté: Sous-éléments ajoutés pour protéger ou embellir les sous-éléments mentionnés ci-dessus', 'Additional equipment: Sub-elements added to protect the embellishment of the above-mentioned sub-elements', 134),
  ('37/8', '37', 2, 'Sous-éléments non décrits ci-dessous', NULL, 135),
  ('38', NULL, 1, 'ELEMENTS DE (3-) NON DECRITS CI-DESSUS, PARAPET - HORIZONTAL', 'OTHER ELEMENTS OF (3-), PARAPET - HORIZONTAL', 136),
  ('38/0', '38', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 137),
  ('38/1', '38', 2, 'Infrastructure: ex. renfort de bord d''ouverture pour fixation du parapet, ...', 'Infrastructure: e.g. reinforcement of edge of opening to attach parapet, ...', 138),
  ('38/2', '38', 2, 'Parties de fermeture : sous-élément qui remplit la fonction de délimitation de l''espace', 'Ending parts: Sub-element that fulfills the actual space-delimiting function', 139),
  ('38/3', '38', 2, 'Structure de support', 'Support structure', 140),
  ('38/4', '38', 2, 'Traitement, finition: ex. couche de peinture, couche de protection du bois', 'Treatment, finishing: e.g. paint layer, wood protection layer', 141),
  ('38/5', '38', 2, 'Installations contenant des fluides (incorporées)', 'Fluid installations (incorporated)', 142),
  ('38/6', '38', 2, 'Installations électriques (incorporées)', 'Electrical installations (incorporated)', 143),
  ('38/7', '38', 2, 'Sous-éléments ajoutés pour protéger ou embellir les sous-éléments mentionnés ci-dessus', 'Sub-elements added to protect the embellishment of the above-mentioned sub-elements', 144),
  ('38/8', '38', 2, 'Sous-éléments non décrits ci-dessous', NULL, 145),
  ('41', NULL, 1, 'FINITIONS EXTERIEURES DES MURS', 'EXTERNAL FINISHES TO WALLS', 146),
  ('41/0', '41', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 147),
  ('41/1', '41', 2, 'Infrastructure : renforcement des murs pour permettre l''accrochage des finitions', 'Infrastructure: reinforcement of walls to allow fixing of finishing', 148),
  ('41/2', '41', 2, 'Revêtement: ex. bardage en ardoise, maçonnerie de façade,...', 'Cladding: e.g. slate cladding, facade masonry,...', 149),
  ('41/3', '41', 2, 'Structure porteuse: Si la différence entre la structure porteuse et le revêtement n''existe pas ou n''est pas pertinente, utiliser le code (41/2)', 'Supporting structure: If the difference between the supporting structure and the cladding does not exist, or not relevant is, use code (41/2)', 150),
  ('41/4', '41', 2, 'Traitement, finition: ex. couche de peinture, couche de protection du bois', 'Treatment, finishing: e.g. paint layer, wood protection layer', 151),
  ('41/5', '41', 2, 'Installations contenant des fluides (incorporées)', 'Fluid installations (incorporated)', 152),
  ('41/6', '41', 2, 'Installations électriques (incorporées)', 'Electrical installations (incorporated)', 153),
  ('41/7', '41', 2, 'Sous-éléments ajoutés pour protéger ou embellir les sous-éléments mentionnés ci-dessus', 'Sub-elements added to protect the embellishment of the above-mentioned sub-elements', 154),
  ('41/8', '41', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 155),
  ('42', NULL, 1, 'FINITIONS INTERIEURES DES MURS', 'INTERNAL FINISHES TO WALLS', 156),
  ('42/0', '42', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 157),
  ('42/1', '42', 2, 'Infrastructure: ex. dépolissage de surfaces à plâtrer,...', 'Infrastructure: e.g. roughening of surface for plastering,...', 158),
  ('42/2', '42', 2, 'Revêtemet: ex. plâtre, plaques de plâtre collées au mur, plaques de plâtre sur cadre en bois (cadre lui-même voir (43/3)), ...', 'Finishing: e.g. plasterwork, plasterboard panels glued to the wall, plasterboard panels on a wooden frame (frame itself see (43/3)), ...', 159),
  ('42/3', '42', 2, 'Structure de support: ex. cadre pour panneaux de plaques de plâtre,...', 'Support structure: e.g. framework for plasterboard panels,...', 160),
  ('42/4', '42', 2, 'Traitement, finition: ex. couche de peinture, couche de protection du bois', 'Treatment, finishing: e.g. paint layer, wood protection layer', 161),
  ('42/5', '42', 2, 'Installations contenant des fluides (incorporées)', 'Fluid installations (incorporated)', 162),
  ('42/6', '42', 2, 'Installations électriques (incorporées)', 'Electrical installations (incorporated)', 163),
  ('42/7', '42', 2, 'Sous-éléments ajoutés pour protéger ou embellir les sous-éléments mentionnés ci-dessus', 'Sub-elements added to protect the embellishment of the above-mentioned sub-elements', 164),
  ('42/8', '42', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 165),
  ('43', NULL, 1, 'FINITIONS DES PLANCHERS', 'FLOOR FINISHES', 166),
  ('43/0', '43', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 167),
  ('43/1', '43', 2, 'Infrastructure: ex. rendre rugueuse la surface pour favoriser l''adhésion des couches, couche de nivellement, couche de remplissage,...', 'Infrastructure: e.g. roughening the surface to promote adhesion of layers, leveling layer, filling layer,...', 168),
  ('43/2', '43', 2, 'Finition: ex. panneaux pour planchers surélevés, carrelage avec couche de mortier, moquette sur colle, parquet,...', 'Finish: e.g. panels for raised floors, tiles with mortar layer, wall-to-wall carpet on adhesive, parquet,...', 169),
  ('43/3', '43', 2, 'Structure de support: ex. système de support pour planchers surélevés', 'Support structure: e.g. support system for raised floors', 170),
  ('43/4', '43', 2, 'Traitement, finition', 'Treatment, Finishing', 171),
  ('43/5', '43', 2, 'Installations contenant des fluides: ex. tuyaux de chauffage inclus dans chape, tuyaux de plomberie inclus dans chape,...', 'Installations fluids: e.g. heating pipes in screed, plumbing pipes in screed,...', 172),
  ('43/6', '43', 2, 'Installations électriques: ex. résistances électriques pour chauffage intégrées dans la chape,...', 'Electrical installations: e.g. electrical resistances for heating integrated in screed,...', 173),
  ('43/7', '43', 2, 'Sous-élément ajouté pour protéger ou embellir ex: plinthe,...', 'Added Sub-element to protect or embellish the above-mentioned sub-elements: e.g. floor plinth,...', 174),
  ('43/8', '43', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 175),
  ('44', NULL, 1, 'FINITIONS DES ESCALIERS, PLANS INCLINES', 'STAIR FINISHES, RAMP FINISHES', 176),
  ('44/0', '44', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 177),
  ('44/1', '44', 2, 'Infrastructure: ex. rendre la surface rugueuse pour favoriser l''adhésion des couches,...', 'Infrastructure: e.g. roughening the surface to promote adhesion of layers,...', 178),
  ('44/2', '44', 2, 'Finition: ex. carrelage avec couche de mortier, revêtement en bois pour marches, moquette collée, ...', 'Finishing: e.g. tiles with mortar layer, wooden covering for steps, glued carpet, ...', 179),
  ('44/3', '44', 2, 'Structure porteuse : Si la différence entre le revêtement et la structure porteuse n''existe pas ou n''est pas pertinente, utiliser le code (44/2)', 'Supporting structure: If the difference between the cladding and the supporting structure does not exist or is not relevant, use code (44/2)', 180),
  ('44/4', '44', 2, 'Traitement, finition', 'Treatment, Finishing', 181),
  ('44/5', '44', 2, 'Installations contenant des fluides (incorporées)', 'Fluid installations (incorporated)', 182),
  ('44/6', '44', 2, 'Installations électriques (incorporées)', 'Electrical installations (incorporated)', 183),
  ('44/7', '44', 2, 'Sous-élément ajouté pour protéger ou embellir ex: plinthe,...', 'Added Sub-element to protect or embellish the above-mentioned sub-elements: e.g. floor plinth,...', 184),
  ('44/8', '44', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 185),
  ('45', NULL, 1, 'FINITIONS DES PLAFONDS', 'CEILING FlNISHES', 186),
  ('45/0', '45', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 187),
  ('45/1', '45', 2, 'Infrastructure: ex. préparation de la surface pour favoriser l''adhésion des couches,...', 'Infrastructure: e.g. surface preparation to improve layer adhesion,...', 188),
  ('45/2', '45', 2, 'Revêtement: ex. couches d''enduit, lattes ou panneaux de faux plafond, plaques de plâtre et et couche d''enduit éventuelle,...', 'Upholstery: e.g. multiple layers of plaster, scraps, slats or false ceiling panels, plasterboard panels and any plaster layer,...', 189),
  ('45/3', '45', 2, 'Structure de support: ex. profilés suspendus pour faux plafonds,...', 'Support structure: e.g. suspended profiles for false ceilings,...', 190),
  ('45/4', '45', 2, 'Traitement, finition', 'Treatment, Finishing', 191),
  ('45/5', '45', 2, 'Installations contenant des fluides: ex. gicleurs incorporés au faux plafond, buses d''extraction et d''alimentation incorporées au faux plafond,...', 'Installations fluids: e.g. sprinkler installation incorporated in false ceiling, extraction and supply nozzles incorporated in false ceiling,...', 192),
  ('45/6', '45', 2, 'Installations électriques: ex. éclairage intégré au faux plafond,...', 'Electrical installations: e.g. lighting integrated in false ceiling,...', 193),
  ('45/7', '45', 2, 'Sous-éléments ajoutés pour protéger et embellir les sous-éléments mentionnés ci-dessus.', 'Sub-elements added to protect and embellish the above-mentioned sub-elements.', 194),
  ('45/8', '45', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 195),
  ('47', NULL, 1, 'FINITIONS EXTERIEURES DES TOITURES', 'ROOF FINISHES (EXTERNAL)', 196),
  ('47/0', '47', 2, 'Démolition, supprimer du modèle', 'Demolition, remove from model', 197),
  ('47/1', '47', 2, 'Infrastructure: ex. préparation de la sous-couche pour que la finition extérieure adhère,...', 'Infrastructure: e.g. preparation of the underlayer so that the exterior finish will adhere,...', 198),
  ('47/2', '47', 2, 'Revêtement extérieur', 'Exterior cladding', 199),
  ('47/3', '47', 2, 'Structure de support: ex. profilés pour soutenir le revête- ment de toiture, construction pour former une pente,...', 'Support structure: e.g. profiles to support roof sheeting, construction to form a slope,...', 200),
  ('47/4', '47', 2, 'Traitement, finition', 'Treatment, Finishing', 201),
  ('47/5', '47', 2, 'Installations contenant des fluides: ex. conduits pour l''évacuation de l''humidité du bâtiment ou de la condensation interne, gargouilles,...', 'Installations fluids: e.g. channels for drainage of construction moisture or internal condensation, spouts,...', 202),
  ('47/6', '47', 2, 'Installations électriques: ex. paratonnerre,...', 'Electrical installations: e.g. lightning rod,...', 203),
  ('47/7', '47', 2, 'Sous-élément ajouté : Sous-éléments ajoutés pour protéger ou embellir les sous-éléments mentionnés ci-dessus', 'Sub-elements added to protect or embellish the above-mentioned sub-elements', 204),
  ('47/8', '47', 2, 'Sous-éléments non décrits ci-dessous', 'Sub-Elements not mentioned before', 205),
  ('52.1', NULL, 1, 'EVACUATION DES IMMONDICES', 'DISPOSAL OF SOLID WASTE', 206),
  ('52.1/0', '52.1', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g.: for transit through other elements', 207),
  ('52.1/1', '52.1', 2, 'Infrastructure: ex. socle pour supporter le conduit d''évacuation', 'Infrastructure: e.g. socle to support drain', 208),
  ('52.1/2', '52.1', 2, 'Sous-éléments primaires: ex. conteneur à déchets sur roues', 'Primary sub-elements: e.g. wheeled waste container', 209),
  ('52.1/3', '52.1', 2, 'Sous-éléments secondaires: ex. tube, conduit', 'Secondary sub-elements: e.g. tube, channel', 210),
  ('52.1/4', '52.1', 2, 'Traitement, finition', 'Treatment, finishing', 211),
  ('52.1/5', '52.1', 2, 'Équipements de traitement secondaire: ex. installation de compactage', 'Secondary treatment equipment: e.g.: compaction equipment', 212),
  ('52.1/6', '52.1', 2, 'Équipement de mesure ou de controle: ex. mesure du niveau de remplissage', 'Equipment for measurement or control: e.g. measurement of filling level', 213),
  ('52.1/7', '52.1', 2, 'Dispositif supplémentaire: ex. Trappes', 'Additional device: e.g. hatches', 214),
  ('52.1/8', '52.1', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 215),
  ('52.2', NULL, 1, 'ÉVACUATION DES RÉSIDUS GAZEUX PAR CANALISATION', 'DISPOSAL OF GASEOUS WASTE VIA CHANNEL', 216),
  ('52.2/0', '52.2', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g. for transit through other elements', 217),
  ('52.2/1', '52.2', 2, 'Infrastructure: ex. socle pour conduit de cheminée', 'Infrastructure: e.g. pedestal for chimney flue', 218),
  ('52.2/2', '52.2', 2, 'Sous-éléments primaires n.a.', 'Primary sub-elements n.a.', 219),
  ('52.2/3', '52.2', 2, 'Sous-éléments secondaires: Conduit d''évacuation y compris accessoires', 'Secondary sub-elements: Drain duct, including accessories', 220),
  ('52.2/4', '52.2', 2, 'Traitement, finition', 'Treatment, finishing', 221),
  ('52.2/5', '52.2', 2, 'Équipements de traitement secondaire des fluides: ex. installation d''extraction', 'Secondary treatment equipment for fluids: e.g. extraction installation', 222),
  ('52.2/6', '52.2', 2, 'Équipement de mesure ou de controle: ex. régulateur de débit', 'Equipment for measurement or control: e.g. flow controller', 223),
  ('52.2/7', '52.2', 2, 'Dispositif supplémentaire', 'Additional device', 224),
  ('52.2/8', '52.2', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 225),
  ('52.3', NULL, 1, 'ÉVACUATION DES EAUX USÉES', 'DISPOSAL OF WASTEWATER', 226),
  ('52.3/0', '52.3', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g. for transit through other elements', 227),
  ('52.3/1', '52.3', 2, 'Infrastructure: ex. fondation pour fosse septique', 'Infrastructure: e.g. foundation for septic tank', 228),
  ('52.3/2', '52.3', 2, 'Sous-éléments primaires: ex. fosse septique', 'Primary sub-elements: e.g. septic tank', 229),
  ('52.3/3', '52.3', 2, 'Sous-éléments secondaires: Tuyaux d''évacuation y compris les accessoires', 'Secondary sub-elements: water evacuation pipes, including accessories', 230),
  ('52.3/4', '52.3', 2, 'Traitement, finition', 'Treatment, finishing', 231),
  ('52.3/5', '52.3', 2, 'Équipement de traitement secondaire des fluides: ex. pompe', 'Secondary treatment equipment for fluids: e.g. pump', 232),
  ('52.3/6', '52.3', 2, 'Équipement de mesure ou de controle: ex. indicateur de niveau', 'Equipment for measuring or control: e.g. level meter', 233),
  ('52.3/7', '52.3', 2, 'Équipements complémentaires: ex. remblais, trappes d''accès.', 'Additional equipment: e.g. ground fills, access hatches', 234),
  ('52.3/8', '52.3', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 235),
  ('52.5', NULL, 1, '​​​​ÉVACUATION DES EAUX NATURELLES', 'DRAINAGE OF RAINWATER', 236),
  ('52.5/0', '52.5', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g. for transit through other elements', 237),
  ('52.5/1', '52.5', 2, 'Infrastructure ex. fondation pour réservoir, pour puisard, pour fosse de controle', 'Infrastructure: e.g. foundation for tank, for sump, for control pit', 238),
  ('52.5/2', '52.5', 2, 'Sous-éléments primaires: Citernes de traitement et de stockage ex. : réservoir d''eau de pluie', 'Primary sub-elements Treatment and storage vessels e.g.: rainwater tank', 239),
  ('52.5/3', '52.5', 2, 'Sous-éléments secondaires Tuyaux d''évacuation y compris accessoires', 'Secondary sub-elements Drain pipes including accessories', 240),
  ('52.5/4', '52.5', 2, 'Traitement, finition', 'Treatment, finishing', 241),
  ('52.5/5', '52.5', 2, 'Équipement de traitement secondaire des fluides: ex. filtre', 'Secondary treatment equipment for fluids: e.g. filter', 242),
  ('52.5/6', '52.5', 2, 'Équipement de mesure ou de controle: ex. indicateur de niveau', 'Equipment for measuring or control: e.g. level meter', 243),
  ('52.5/7', '52.5', 2, 'Dispositif ajouté', 'Added device', 244),
  ('52.5/8', '52.5', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 245),
  ('53.1', NULL, 1, 'DISTRIBUTION D'' EAU FROIDE', 'COLD WATER SUPPLY', 246),
  ('53.1/0', '53.1', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g. for transit through other elements', 247),
  ('53.1/1', '53.1', 2, 'Infrastructure: ex. fondation pour réservoir', 'Infrastructure: e.g. foundation for tank', 248),
  ('53.1/2', '53.1', 2, 'Sous-éléments primaires', 'Primary sub-elements', 249),
  ('53.1/3', '53.1', 2, 'Sous-éléments secondaires: tuyaux de distribution', 'Secondary sub-elements: distribution pipes', 250),
  ('53.1/4', '53.1', 2, 'Traitement, finition: ex. traitement antirouille', 'Treatment, finishing: e.g. anti-rust treatment', 251),
  ('53.1/5', '53.1', 2, 'Équipement de traitement secondaires: ex. chauffage de l''eau, ballon de stockage d''eau chaude, pompe de circulation', 'Secondary fluid treatment equipment: e.g. water heating, hot water storage tank', 252),
  ('53.1/6', '53.1', 2, 'Équipement de mesure ou de controle: ex. débitmètre, régulateur de débit', 'Equipment for measuring or control: e.g. flow meter, flow controller', 253),
  ('53.1/7', '53.1', 2, 'Dispositif supplémentaire', 'Additional device', 254),
  ('53.1/8', '53.1', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 255),
  ('53.7', NULL, 1, 'DISTRIBUTION DE CONBUSTIBLES LIQUIDE', 'SUPPLY OF PETROL, OIL', 256),
  ('53.7/0', '53.7', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g. for transit through other elements', 257),
  ('53.7/1', '53.7', 2, 'Infrastructure: ex. : fondation pour réservoir', 'Infrastructure: e.g. foundation for tank', 258),
  ('53.7/2', '53.7', 2, 'Sous-éléments primaires: ex. réservoir de mazout', 'Primary sub-elements: e.g. oil tank', 259),
  ('53.7/3', '53.7', 2, 'Sous-éléments secondaires: tuyaux de distribution', 'Secondary sub-elements: distribution pipes', 260),
  ('53.7/4', '53.7', 2, 'Traitement finition: ex. Traitement anticorrosion', 'Treatment, inishing: e.g. Anti-corrosion treatment', 261),
  ('53.7/5', '53.7', 2, 'Équipement de traitement des fluides secondaires Ex : pompe de circulation, filtre', 'Secondary fluid treatment equipment: e.g. circulation pump, filter', 262),
  ('53.7/6', '53.7', 2, 'Équipement de mesure ou de controle: ex. mesure de pression', 'Equipment for measuring or control: e.g. pressure measurement', 263),
  ('53.7/7', '53.7', 2, 'Dispositif ajouté Ex : remblais, couvercle', 'Added device: e.g. ground fills, cover', 264),
  ('53.7/8', '53.7', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 265),
  ('54.1', NULL, 1, 'DISTRIBUTION DE GAZ COMBUSTIBLE', 'SUPPLY OF COMBUSTIBLE GAS', 266),
  ('54.1/0', '54.1', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g. for transit through other elements', 267),
  ('54.1/1', '54.1', 2, 'Infrastructure: ex. fondation pour réservoir', 'Infrastructure: e.g. foundation for tank', 268),
  ('54.1/2', '54.1', 2, 'Sous-éléments primaires: ex. réservoir de gaz', 'Primary sub-elements e.g.: gas tank', 269),
  ('54.1/3', '54.1', 2, 'Sous-éléments secondaires ex. tuyaux', 'Secondary sub-elements e.g. pipes', 270),
  ('54.1/4', '54.1', 2, 'Traitement, finition: ex. traitement antirouille', 'Treatment, finishing: e.g. Anti-rust treatment', 271),
  ('54.1/5', '54.1', 2, 'Équipements de traitement secondaire des fluides: ex. pompe de circulation', 'Secondary treatment equipment for fluids: e.g. circulation pump', 272),
  ('54.1/6', '54.1', 2, 'Équipement de mesure ou de controle: ex. manomètre, régulateur de pression', 'Equipment for measuring or control: e.g. pressure gauge, pressure regulator', 273),
  ('54.1/7', '54.1', 2, 'Dispositif ajouté: ex. remblais, couvercle', 'Added device: e.g. ground fills, cover', 274),
  ('54.1/8', '54.1', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 275),
  ('55.1', NULL, 1, 'REFRIGERATION CENTRALE PAR LIQUIDE (PAS AVEC AIR)', 'CENTRAL COOLING SYSTEM VIA COOLANT (NOT WITH AIR)', 276),
  ('55.1/0', '55.1', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g. for transit through other elements', 277),
  ('55.1/1', '55.1', 2, 'Infrastructure: ex. base pour refroidisseur', 'Infrastructure: e.g. base for cooling machine', 278),
  ('55.1/2', '55.1', 2, 'Sous-éléments primaires : Cuves de traitement et de stockage: ex. réservoir d''eau glacée, refroidisseur, tuyaux d''alimentation', 'Primary sub-elements Treatment and storage vessels: e.g. ice water buffer tank, chiller, supply pipes including accessories', 279),
  ('55.1/3', '55.1', 2, 'Sous-éléments secondaires: Éléments pour échange de froid Ex. : plafond ou mur rafraîchissant, conduites de distribution + accessoires', 'Secondary sub-elements: Elements for cold exchange e.g.: cooling ceiling, cooling wall, distribution pipes including accessories', 280),
  ('55.1/4', '55.1', 2, 'Traitement, finition', 'Treatment, finishing', 281),
  ('55.1/5', '55.1', 2, 'Équipement de traitement secondaire des fluides: ex. circulateur', 'Secondary treatment equipment for fluids: e.g. circulation pump', 282),
  ('55.1/6', '55.1', 2, 'Équipement de mesure ou de controle: ex. capteur de température régulateur de débit', 'Equipment for measuring or control: e.g temperature sensor, thermostat', 283),
  ('55.1/7', '55.1', 2, 'Dispositif ajouté Ex : boîtier de protection', 'Additional equipment: e.g. shielding box', 284),
  ('55.1/8', '55.1', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 285),
  ('56.4', NULL, 1, 'CHAUFFAGE CENTRAL à CHAUDE OU VAPEUR', 'CENTRAL HEATING VIA HOT WATER OR STEAM', 286),
  ('56.4/0', '56.4', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g. for transit through other elements', 287),
  ('56.4/1', '56.4', 2, 'Infrastructure: ex. socle pour chaudière', 'Infrastructure: e.g. base for boiler', 288),
  ('56.4/2', '56.4', 2, 'Sous-éléments primaires Vases de traitement et de stockage: ex. chaudière à gaz, vase d''expansion, pompe à chaleur', 'Primary sub-elements Treatment and storage vessels: e.g. gas boiler, expansion vessel, heat pump', 289),
  ('56.4/3', '56.4', 2, 'Sous-éléments secondaires: Éléments pour échange de chaleur ex. Radiateur, tuyaux dans le sol pour le chauffage, conduites de distribution y compris accessoires', 'Secondary sub-elements: Delivery elements: e.g. radiator, pipes in floor for heating, ducts including accessories', 290),
  ('56.4/4', '56.4', 2, 'Traitement, finition: ex. traitement antirouille', 'Treatment, finishing: e.g. anti-rust treatment', 291),
  ('56.4/5', '56.4', 2, 'Équipement de traitement secondaire des fluides: ex. circulateur', 'Secondary fluid treatment equipment: e.g. circulation pump', 292),
  ('56.4/6', '56.4', 2, 'Équipement de mesure ou de régulation: ex. régulateur de débit, sonde de température, thermostat', 'Equipment for measuring or control: e.g. flow controller, temperature sensor, thermostat', 293),
  ('56.4/7', '56.4', 2, 'Équipement supplémentaire', 'Additional equipment', 294),
  ('56.4/8', '56.4', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 295),
  ('57.N', NULL, 1, 'CONDITIONNEMENT D'' AIR ET VENTILATION', 'AIR TREATMENT AND VENTILATION', 296),
  ('57.N/0', '57.N', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'Demolition, remove from model: e.g. for transit through other elements', 297),
  ('57.N/1', '57.N', 2, 'Infrastructure: ex. socle pour unité de traitement de l''air', 'Infrastructure: e.g. base for air handling unit', 298),
  ('57.N/2', '57.N', 2, 'Sous-éléments primaires', 'Primary sub-elements', 299),
  ('57.N/3', '57.N', 2, 'Sous-éléments secondaires Éléments de diffusion ex. grille d''aération', 'Secondary sub-elements Heat Release elements e.g. ventilation grille', 300),
  ('57.N/4', '57.N', 2, 'Traitement, finition: ex. traitement anti-feu', 'Treatment, finishing: e.g. fire-resistant treatment', 301),
  ('57.N/5', '57.N', 2, 'traitement second: ex. humidificateur local, réchauffeur d''air local, filtre local', 'Secondary treatment: e.g. local humidifier, local air reheater, local filter', 302),
  ('57.N/6', '57.N', 2, 'Équipements de mesure ou de controle: ex. capteur de tem- pérature, régulateur de débit, capteur de CO2', 'Equipment for measurement or control: e.g. temperature sensor, flow controller, CO2 sensor', 303),
  ('57.N/7', '57.N', 2, 'Équipements complémentaires: ex. panneaux de revêtement fixes ou amovibles', 'Additional equipment: e.g. fixed or removable cladding panels', 304),
  ('57.N/8', '57.N', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 305),
  ('62', NULL, 1, 'RÉSEAU ÉLECTRIQUE SECONDAIRE', 'SECONDARY ELECTRICITY NETWORK', 306),
  ('62/0', '62', 2, 'Démolition, supprimer du modèle: ex. pour le passage à travers d''autres éléments', 'SECONDARY ELECTRICITY NETWORK Demolition, remove from model: e.g.: for transit through other elements', 307),
  ('62/1', '62', 2, 'Infrastructure: ex. socle, structure porteuse pour panneau photovoltaïque', 'Infrastructure: e.g. plinth, supporting structure for PV panel', 308),
  ('62/2', '62', 2, 'Sous-éléments primaires', 'Primary sub-elements', 309),
  ('62/3', '62', 2, 'Sous-éléments secondaires: fils électriques, interrupteurs, fiches', 'Secondary sub-elements: electrical wires, switches, plugs', 310),
  ('62/4', '62', 2, 'Traitement, finition: ex. protection contre les UV ou l''eau', 'Treatment, finishing: e.g. protection against UV or water', 311),
  ('62/5', '62', 2, 'Équipements de traitement secondaire de l''électricité: ex. batterie, transformateur à faible courant', 'Equipment for secondary treatment of electricity: e.g. battery, transformer to low-current', 312),
  ('62/6', '62', 2, 'Équipement de mesure ou de controle: ex. compteur de consommation, Voltmètre', 'Equipment for measurement or control: e.g. consumption meter, voltage meter', 313),
  ('62/7', '62', 2, 'Équipements supplémentaires', 'Additional equipment', 314),
  ('62/8', '62', 2, 'Sous-éléments non mentionnés ci-dessus', 'Sub-elements not mentioned above', 315)
ON CONFLICT (code) DO UPDATE SET parent_code = EXCLUDED.parent_code, niveau = EXCLUDED.niveau, libelle = EXCLUDED.libelle, libelle_en = EXCLUDED.libelle_en, position = EXCLUDED.position;

-- Corps d'état de la nomenclature FFB : 23 métiers en 4 familles.
INSERT INTO ref_corps_etat (code, famille, libelle, position) VALUES
  ('structure.sols-et-fondations', 'STRUCTURE', 'Sols et fondations', 1),
  ('structure.maconnerie-beton', 'STRUCTURE', 'Maçonnerie - Béton', 2),
  ('structure.construction-metallique', 'STRUCTURE', 'Construction métallique', 3),
  ('structure.construction-en-bois', 'STRUCTURE', 'Construction en bois', 4),
  ('enveloppe.facades-revetements-de-facades', 'ENVELOPPE', 'Façades - Revêtements de façades', 5),
  ('enveloppe.isolation-thermique-par-l-exterieur', 'ENVELOPPE', 'Isolation thermique par l''extérieur', 6),
  ('enveloppe.menuiserie-fermeture', 'ENVELOPPE', 'Menuiserie - Fermeture', 7),
  ('enveloppe.miroiterie-vitrerie', 'ENVELOPPE', 'Miroiterie - Vitrerie', 8),
  ('enveloppe.couverture', 'ENVELOPPE', 'Couverture', 9),
  ('enveloppe.etancheite', 'ENVELOPPE', 'Etanchéité', 10),
  ('amenagements-interieurs.enduits-et-projections', 'AMENAGEMENTS INTERIEURS', 'Enduits et projections', 11),
  ('amenagements-interieurs.cloisons-et-doublages', 'AMENAGEMENTS INTERIEURS', 'Cloisons et doublages', 12),
  ('amenagements-interieurs.menuiseries-interieures', 'AMENAGEMENTS INTERIEURS', 'Menuiseries intérieures', 13),
  ('amenagements-interieurs.plafonds', 'AMENAGEMENTS INTERIEURS', 'Plafonds', 14),
  ('amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves', 'AMENAGEMENTS INTERIEURS', 'Revêtements de sols - Chapes - Planchers surélevés', 15),
  ('amenagements-interieurs.peinture-et-revetements-de-finition', 'AMENAGEMENTS INTERIEURS', 'Peinture et revêtements de finition', 16),
  ('equipements-techniques.plomberie-assainissement', 'EQUIPEMENTS TECHNIQUES', 'Plomberie - Assainissement', 17),
  ('equipements-techniques.gaz', 'EQUIPEMENTS TECHNIQUES', 'Gaz', 18),
  ('equipements-techniques.chauffage', 'EQUIPEMENTS TECHNIQUES', 'Chauffage', 19),
  ('equipements-techniques.fumisterie', 'EQUIPEMENTS TECHNIQUES', 'Fumisterie', 20),
  ('equipements-techniques.ventilation', 'EQUIPEMENTS TECHNIQUES', 'Ventilation', 21),
  ('equipements-techniques.isolation-thermique-froid', 'EQUIPEMENTS TECHNIQUES', 'Isolation thermique - Froid', 22),
  ('equipements-techniques.installations-electriques', 'EQUIPEMENTS TECHNIQUES', 'Installations électriques', 23)
ON CONFLICT (code) DO UPDATE SET famille = EXCLUDED.famille, libelle = EXCLUDED.libelle, position = EXCLUDED.position;

-- NF DTU (BNTEC/FFB, janvier 2026) : 115 normes.
INSERT INTO ref_dtu (code, prefixe, numero, titre, norme, amendement) VALUES
  ('NF DTU 13.1', 'NF DTU', '13.1', 'Fondations superficielles', 'P11-201', FALSE),
  ('NF DTU 13.2', 'NF DTU', '13.2', 'Fondations profondes', 'P94-253', FALSE),
  ('NF DTU 13.3', 'NF DTU', '13.3', 'Dallages - Conception, calcul et exécution', 'P11-213', FALSE),
  ('NF DTU 14.1', 'NF DTU', '14.1', 'Travaux de cuvelage', 'P11-221', FALSE),
  ('NF DTU 20.1', 'NF DTU', '20.1', 'Ouvrages en maçonnerie de petits éléments – Parois et murs', 'P10-202', FALSE),
  ('NF DTU 20.12', 'NF DTU', '20.12', 'Gros œuvre en maçonnerie des toitures destinées à recevoir un revêtement d’étanchéité', 'P10-203', TRUE),
  ('NF DTU 20.13', 'NF DTU', '20.13', 'Cloisons en maçonnerie de petits éléments', 'P10-204', TRUE),
  ('NF DTU 21', 'NF DTU', '21', 'Exécution des ouvrages en béton', 'P18-201', FALSE),
  ('NF DTU 22.1', 'NF DTU', '22.1', 'Murs extérieurs en panneaux préfabriqués de grandes dimensions du type plaque pleine ou nervurée en béton ordinaire', 'P10-210', FALSE),
  ('NF DTU 23.1', 'NF DTU', '23.1', 'Murs en béton banché', 'P18-210', FALSE),
  ('NF DTU 23.2', 'NF DTU', '23.2', 'Planchers à dalles alvéolées préfabriquées en béton', 'P19-201', FALSE),
  ('NF DTU 23.3', 'NF DTU', '23.3', 'Ossatures en éléments industrialisés en béton', 'P19-202', FALSE),
  ('NF DTU 23.4', 'NF DTU', '23.4', 'Planchers à prédalles industrialisées en béton', 'P19-203', FALSE),
  ('NF DTU 23.5', 'NF DTU', '23.5', 'Planchers à poutrelles en béton', 'P19-204', FALSE),
  ('NF DTU 32.1', 'NF DTU', '32.1', 'Charpentes et ossatures en acier', 'P22-201', FALSE),
  ('NF DTU 32.3', 'NF DTU', '32.3', 'Construction d''ossatures en acier pour maisons et bâtiments résidentiels', 'P22-203', FALSE),
  ('NF DTU 31.1', 'NF DTU', '31.1', 'Charpente en bois', 'P21-203', FALSE),
  ('NF DTU 31.2', 'NF DTU', '31.2', 'Construction de maisons et bâtiments à ossature en bois', 'P21-204', FALSE),
  ('NF DTU 31.3', 'NF DTU', '31.3', 'Charpentes en bois assemblées par connecteurs métalliques ou goussets', 'P21-205', TRUE),
  ('NF DTU 31.4', 'NF DTU', '31.4', 'Façades à ossature bois', 'P21-206', FALSE),
  ('NF DTU 26.1', 'NF DTU', '26.1', 'Travaux d’enduits de mortiers', 'P15-201', FALSE),
  ('NF DTU 33.1', 'NF DTU', '33.1', 'Façades rideaux', 'P28-002', FALSE),
  ('XP DTU 33.2', 'XP DTU', '33.2', 'Tolérances dimensionnelles du gros œuvre destiné à recevoir des façades rideaux, semi-rideaux ou panneaux', 'XPP28-003', FALSE),
  ('NF DTU 41.2', 'NF DTU', '41.2', 'Revêtements extérieurs en bois', 'P65-210', FALSE),
  ('NF DTU 42.1', 'NF DTU', '42.1', 'Réfection de façades en service par revêtements d’imperméabilité à base de polymères', 'P84-404', FALSE),
  ('NF DTU 44.1', 'NF DTU', '44.1', 'Étanchéité des joints de façade par mise en œuvre de mastics', 'P85-210', FALSE),
  ('NF DTU 52.2', 'NF DTU', '52.2', 'Pose collée des revêtements céramiques et assimilés – Pierres naturelles', 'P61-204', FALSE),
  ('NF DTU 55.2', 'NF DTU', '55.2', 'Revêtements muraux attachés en pierre mince', 'P65-202', TRUE),
  ('FD DTU 45.3', 'FD DTU', '45.3', 'Bâtiments neufs isolés thermiquement par l''extérieur - Guide de conception des bâtiments et de rédaction des documents particuliers du marché (DPM)', 'P75-463', FALSE),
  ('NF DTU 45.4', 'NF DTU', '45.4', 'Systèmes d''isolation thermique par l''extérieur en bardage rapporté avec lame d''air ventilée', 'P75-503', FALSE),
  ('NF DTU 34.1', 'NF DTU', '34.1', 'Mise en œuvre des portes et portails industriels, commerciaux et résidentiels', 'P25-201', FALSE),
  ('FD DTU 34.3', 'FD DTU', '34.3', 'Choix des portes industrielles, commerciales et de garage en fonction de leur exposition au vent', 'P25-203', FALSE),
  ('NF DTU 34.4', 'NF DTU', '34.4', 'Mise en œuvre des fermetures et stores', 'P25-204', FALSE),
  ('NF DTU 34.5', 'NF DTU', '34.5', 'Mise en œuvre des blocs-portes motorisés pour piétons', 'P25-205', FALSE),
  ('NF DTU 36.5', 'NF DTU', '36.5', 'Mise en œuvre des fenêtres et portes extérieures', 'P20-202', FALSE),
  ('NF DTU 39', 'NF DTU', '39', 'Travaux de vitrerie–miroiterie', 'P78-201', FALSE),
  ('FD DTU 39', 'FD DTU', '39', 'Travaux de vitrerie–miroiterie – Partie 5 : Mémento pour les maîtres d''œuvre', 'P78-201-5', FALSE),
  ('NF DTU 40.11', 'NF DTU', '40.11', 'Couverture en ardoises naturelles', 'P32-201', FALSE),
  ('NF DTU 40.13', 'NF DTU', '40.13', 'Couverture en ardoises en fibres-ciment', 'P32-202', TRUE),
  ('NF DTU 40.14', 'NF DTU', '40.14', 'Couverture en bardeaux bitumés', 'P39-201', TRUE),
  ('NF DTU 40.21', 'NF DTU', '40.21', 'Couverture en tuiles de terre cuite à emboîtement ou à glissement à relief', 'P31-202', FALSE),
  ('NF DTU 40.211', 'NF DTU', '40.211', 'Couvertures en tuiles de terre cuite à emboîtement à pureau plat', 'P31-203', FALSE),
  ('NF DTU 40.22', 'NF DTU', '40.22', 'Couverture en tuiles canal de terre cuite', 'P31-201', TRUE),
  ('NF DTU 40.23', 'NF DTU', '40.23', 'Couvertures en tuiles plates de terre cuite', 'P31-204', TRUE),
  ('NF DTU 40.24', 'NF DTU', '40.24', 'Couverture en tuiles en béton à glissement et à emboîtement longitudinal', 'P31-207', FALSE),
  ('NF DTU 40.241', 'NF DTU', '40.241', 'Couvertures en tuiles planes en béton à glissement et à emboîtement longitudinal', 'P31-205', FALSE),
  ('NF DTU 40.25', 'NF DTU', '40.25', 'Couverture en tuiles plates en béton', 'P31-206', TRUE),
  ('NF DTU 40.29', 'NF DTU', '40.29', 'Mise en œuvre des écrans souples de sous toiture', 'P31-208', FALSE),
  ('NF DTU 40.35', 'NF DTU', '40.35', 'Couverture en plaques nervurées issues de tôles d’acier revêtues', 'P34-205', TRUE),
  ('NF DTU 40.36', 'NF DTU', '40.36', 'Couverture en plaques nervurées d’aluminium prélaqué ou non', 'P34-206', FALSE),
  ('NF DTU 40.37', 'NF DTU', '40.37', 'Couverture en plaques ondulées en fibres-ciment', 'P34-203', FALSE),
  ('NF DTU 40.41', 'NF DTU', '40.41', 'Couverture par éléments métalliques en feuilles et longues feuilles en zinc', 'P34-211', FALSE),
  ('NF DTU 40.44', 'NF DTU', '40.44', 'Couvertures par éléments métalliques en feuilles et longues feuilles en acier inoxydable', 'P34-214', FALSE),
  ('NF DTU 40.45', 'NF DTU', '40.45', 'Couverture par éléments métalliques en feuilles et longues feuilles de cuivre', 'P34-215', TRUE),
  ('NF DTU 40.46', 'NF DTU', '40.46', 'Travaux de couverture en plomb sur support continu', 'P34-216', TRUE),
  ('XP DTU 40.5', 'XP DTU', '40.5', 'Travaux d’évacuation des eaux pluviales', 'P36-201', TRUE),
  ('NF DTU 43.1', 'NF DTU', '43.1', 'Étanchéité des toitures-terrasses et toitures inclinées avec éléments porteurs en maçonnerie en climat de plaine', 'P84-204', TRUE),
  ('NF DTU 43.11', 'NF DTU', '43.11', 'Étanchéité des toitures-terrasses et toitures inclinées avec éléments porteurs en maçonnerie en climat de montagne', 'P84-211', FALSE),
  ('NF DTU 43.3', 'NF DTU', '43.3', 'Mise en œuvre des toitures en tôles d’acier nervurées avec revêtement d’étanchéité', 'P84-206', TRUE),
  ('NF DTU 43.4', 'NF DTU', '43.4', 'Toitures en éléments porteurs en bois et panneaux dérivés du bois avec revêtement d’étanchéité', 'P84-207', FALSE),
  ('NF DTU 43.5', 'NF DTU', '43.5', 'Réfection des ouvrages d’étanchéité des toitures-terrasses ou inclinées', 'P84-208', TRUE),
  ('NF DTU 43.6', 'NF DTU', '43.6', 'Étanchéité des planchers intérieurs en maçonnerie par produits hydrocarbonés', 'P84-210', FALSE),
  ('NF DTU 25.1', 'NF DTU', '25.1', 'Enduits intérieurs en plâtre', 'P71-201', FALSE),
  ('NF DTU 27.1', 'NF DTU', '27.1', 'Revêtements par projection pneumatique de fibres minérales de laitier avec liant', 'P15-202', TRUE),
  ('NF DTU 27.2', 'NF DTU', '27.2', 'Réalisation de revêtements par projection de produits pâteux', 'P15-203', TRUE),
  ('NF DTU 25.31', 'NF DTU', '25.31', 'Ouvrages en carreaux de plâtre', 'P72-202', FALSE),
  ('NF DTU 25.41', 'NF DTU', '25.41', 'Ouvrages en plaques en plâtre - Plaques à faces cartonnées', 'P72-203', FALSE),
  ('NF DTU 25.42', 'NF DTU', '25.42', 'Ouvrages de doublage et habillage en complexes et sandwiches plaques de parement en plâtre et isolant', 'P72-204', FALSE),
  ('NF DTU 35.1', 'NF DTU', '35.1', 'Cloisons démontables', 'P24-802', FALSE),
  ('NF DTU 36.2', 'NF DTU', '36.2', 'Menuiseries intérieures et agencement, bois et autres matériaux', 'P23-202', FALSE),
  ('NF DTU 36.3', 'NF DTU', '36.3', 'Escaliers en bois et garde-corps associés', 'P21-220', FALSE),
  ('NF DTU 25.231', 'NF DTU', '25.231', 'Plafonds suspendus en éléments de terre cuite', 'P68-202', FALSE),
  ('NF DTU 25.51', 'NF DTU', '25.51', 'Mise en œuvre des ouvrages en staff traditionnel', 'P73-201', TRUE),
  ('NF DTU 58.1', 'NF DTU', '58.1', 'Plafonds suspendus', 'P68-203', FALSE),
  ('NF DTU 58.2', 'NF DTU', '58.2', 'Plafonds tendus', 'P69-002', FALSE),
  ('NF DTU 26.2', 'NF DTU', '26.2', 'Chapes et dalles à base de liants hydrauliques', 'P14-201', TRUE),
  ('NF DTU 51.1', 'NF DTU', '51.1', 'Pose des parquets à clouer', 'P63-201', TRUE),
  ('NF DTU 51.11', 'NF DTU', '51.11', 'Parquets flottants', 'P63-204', FALSE),
  ('NF DTU 51.2', 'NF DTU', '51.2', 'Parquets collés', 'P63-202', FALSE),
  ('NF DTU 51.3', 'NF DTU', '51.3', 'Planchers en bois ou en panneaux à base de bois', 'P63-203', TRUE),
  ('NF DTU 51.4', 'NF DTU', '51.4', 'Platelages extérieurs en bois', 'P63-205', FALSE),
  ('NF DTU 52.1', 'NF DTU', '52.1', 'Revêtements de sol scellés', 'P61-202', FALSE),
  ('NF DTU 52.10', 'NF DTU', '52.10', 'Mise en œuvre de sous-couches isolantes sous chape ou dalle flottantes et sous carrelage scellé', 'P61-203', FALSE),
  ('NF DTU 53.12', 'NF DTU', '53.12', 'Préparation du support et revêtements de sol souples', 'P62-207', FALSE),
  ('NF DTU 54.1', 'NF DTU', '54.1', 'Revêtements de sol coulés à base de résine de synthèse', 'P62-206', FALSE),
  ('NF DTU 57.1', 'NF DTU', '57.1', 'Planchers surélevés (à libre accès) - Eléments constitutifs - Exécution', 'P67-103', FALSE),
  ('NF DTU 59.1', 'NF DTU', '59.1', 'Revêtements de peinture en feuil mince, semi-épais ou épais', 'P74-201', FALSE),
  ('NF DTU 59.3', 'NF DTU', '59.3', 'Peinture de sols', 'P74-203', FALSE),
  ('NF DTU 59.4', 'NF DTU', '59.4', 'Mise en œuvre des papiers peints et des revêtements muraux', 'P74-204', FALSE),
  ('NF DTU 59.5', 'NF DTU', '59.5', 'Mise en œuvre des revêtements et systèmes intumescents sur structures métalliques', 'P22-204', FALSE),
  ('NF DTU 60.1', 'NF DTU', '60.1', 'Plomberie sanitaire pour bâtiments', 'P40-201', TRUE),
  ('NF DTU 60.11', 'NF DTU', '60.11', 'Règles de calcul des installations de plomberie sanitaire et d''eaux pluviales', 'P40-202', FALSE),
  ('NF DTU 60.2', 'NF DTU', '60.2', 'Canalisations en fonte - Évacuation d''eaux usées, d''eaux vannes et d''eaux pluviales', 'P41-220', FALSE),
  ('NF DTU 60.31', 'NF DTU', '60.31', 'Canalisations en chlorure de polyvinyle non plastifié : eau froide avec pression', 'P41-211', FALSE),
  ('NF DTU 60.32', 'NF DTU', '60.32', 'Canalisations en polychlorure de vinyle non plastifié - Evacuation des eaux pluviales', 'P41-212', FALSE),
  ('NF DTU 60.33', 'NF DTU', '60.33', 'Canalisations en polychlorure de vinyle non plastifié - Evacuation d’eaux usées et d’eaux vannes', 'P41-213', FALSE),
  ('NF DTU 60.5', 'NF DTU', '60.5', 'Canalisations en cuivre - Distribution d’eau froide et chaude sanitaire, évacuation d’eaux usées, d’eaux pluviales, installations de génie climatique', 'P41-221', FALSE),
  ('NF DTU 64.1', 'NF DTU', '64.1', 'Dispositifs d''assainissement non collectif (dit autonome) - Pour les maisons d''habitation individuelle jusqu''à 20 pièces principales', 'P16-603', FALSE),
  ('NF DTU 61.1', 'NF DTU', '61.1', 'Installations de gaz dans les locaux d’habitation', 'P45-204', TRUE),
  ('NF DTU 65.3', 'NF DTU', '65.3', 'Travaux relatifs aux installations de sous-stations d''échange à eau chaude sous pression', 'P52-211', TRUE),
  ('NF DTU 65.4', 'NF DTU', '65.4', 'Chaufferies aux gaz et aux hydrocarbures liquéfiés', 'P52-221', FALSE),
  ('NF DTU 65.7', 'NF DTU', '65.7', 'Exécution des planchers chauffants par câbles électriques enrobés dans le béton', 'P52-302', TRUE),
  ('NF DTU 65.9', 'NF DTU', '65.9', 'Installations de transport de chaleur ou de froid et d''eau chaude sanitaire entre productions de chaleur ou de froid et bâtiments', 'P52-304', TRUE),
  ('NF DTU 65.11', 'NF DTU', '65.11', 'Dispositifs de sécurité des installations de chauffage central concernant le bâtiment', 'P52-203', FALSE),
  ('NF DTU 65.12', 'NF DTU', '65.12', 'Installations solaires thermiques avec des capteurs vitrés', 'P50-601', FALSE),
  ('NF DTU 65.14', 'NF DTU', '65.14', 'Exécution de planchers chauffants à eau chaude', 'P52-307', FALSE),
  ('NF DTU 65.16', 'NF DTU', '65.16', 'Installations de pompes à chaleur', 'P52-310', FALSE),
  ('NF DTU 24.1', 'NF DTU', '24.1', 'Travaux de fumisterie - Installation de systèmes d''évacuation des produits de combustion desservant un ou des appareils', 'P51-201', FALSE),
  ('NF DTU 24.2', 'NF DTU', '24.2', 'Travaux d’âtrerie', 'P51-202', TRUE),
  ('NF DTU 68.3', 'NF DTU', '68.3', 'Installations de ventilation mécanique', 'P50-413', TRUE),
  ('NF DTU 45.1', 'NF DTU', '45.1', 'Isolation thermique des bâtiments frigorifiques et des locaux à ambiance régulée', 'P75-401', FALSE),
  ('NF DTU 45.2', 'NF DTU', '45.2', 'Isolation thermique des circuits, appareils et accessoires de -80°C à + 650°C', 'P75-402', FALSE),
  ('NF DTU 45.10', 'NF DTU', '45.10', 'Isolation des combles par panneaux ou rouleaux en laines minérales manufacturées', 'P75-501', FALSE),
  ('NF DTU 45.11', 'NF DTU', '45.11', 'Isolation thermique de combles par soufflage d’isolant en vrac (laines minérales ou ouate de cellulose de papier)', 'P75-502', FALSE),
  ('NF DTU 70.1', 'NF DTU', '70.1', 'Installations électriques des bâtiments à usage d’habitation', 'P80-201-2', FALSE)
ON CONFLICT (code) DO UPDATE SET prefixe = EXCLUDED.prefixe, numero = EXCLUDED.numero, titre = EXCLUDED.titre, norme = EXCLUDED.norme, amendement = EXCLUDED.amendement;

-- Rattachement DTU / corps d'état : 121 liens.
INSERT INTO ref_dtu_corps_etat (dtu_code, corps_etat_code) VALUES
  ('NF DTU 13.1', 'structure.sols-et-fondations'),
  ('NF DTU 13.2', 'structure.sols-et-fondations'),
  ('NF DTU 13.3', 'structure.sols-et-fondations'),
  ('NF DTU 14.1', 'structure.sols-et-fondations'),
  ('NF DTU 20.1', 'structure.maconnerie-beton'),
  ('NF DTU 20.12', 'structure.maconnerie-beton'),
  ('NF DTU 20.13', 'structure.maconnerie-beton'),
  ('NF DTU 21', 'structure.maconnerie-beton'),
  ('NF DTU 22.1', 'structure.maconnerie-beton'),
  ('NF DTU 23.1', 'structure.maconnerie-beton'),
  ('NF DTU 23.2', 'structure.maconnerie-beton'),
  ('NF DTU 23.3', 'structure.maconnerie-beton'),
  ('NF DTU 23.4', 'structure.maconnerie-beton'),
  ('NF DTU 23.5', 'structure.maconnerie-beton'),
  ('NF DTU 32.1', 'structure.construction-metallique'),
  ('NF DTU 32.3', 'structure.construction-metallique'),
  ('NF DTU 31.1', 'structure.construction-en-bois'),
  ('NF DTU 31.2', 'structure.construction-en-bois'),
  ('NF DTU 31.3', 'structure.construction-en-bois'),
  ('NF DTU 31.4', 'structure.construction-en-bois'),
  ('NF DTU 26.1', 'enveloppe.facades-revetements-de-facades'),
  ('NF DTU 33.1', 'enveloppe.facades-revetements-de-facades'),
  ('XP DTU 33.2', 'enveloppe.facades-revetements-de-facades'),
  ('NF DTU 41.2', 'enveloppe.facades-revetements-de-facades'),
  ('NF DTU 42.1', 'enveloppe.facades-revetements-de-facades'),
  ('NF DTU 44.1', 'enveloppe.facades-revetements-de-facades'),
  ('NF DTU 52.2', 'enveloppe.facades-revetements-de-facades'),
  ('NF DTU 55.2', 'enveloppe.facades-revetements-de-facades'),
  ('FD DTU 45.3', 'enveloppe.isolation-thermique-par-l-exterieur'),
  ('NF DTU 45.4', 'enveloppe.isolation-thermique-par-l-exterieur'),
  ('NF DTU 34.1', 'enveloppe.menuiserie-fermeture'),
  ('FD DTU 34.3', 'enveloppe.menuiserie-fermeture'),
  ('NF DTU 34.4', 'enveloppe.menuiserie-fermeture'),
  ('NF DTU 34.5', 'enveloppe.menuiserie-fermeture'),
  ('NF DTU 36.5', 'enveloppe.menuiserie-fermeture'),
  ('NF DTU 39', 'enveloppe.miroiterie-vitrerie'),
  ('FD DTU 39', 'enveloppe.miroiterie-vitrerie'),
  ('NF DTU 40.11', 'enveloppe.couverture'),
  ('NF DTU 40.13', 'enveloppe.couverture'),
  ('NF DTU 40.14', 'enveloppe.couverture'),
  ('NF DTU 40.21', 'enveloppe.couverture'),
  ('NF DTU 40.211', 'enveloppe.couverture'),
  ('NF DTU 40.22', 'enveloppe.couverture'),
  ('NF DTU 40.23', 'enveloppe.couverture'),
  ('NF DTU 40.24', 'enveloppe.couverture'),
  ('NF DTU 40.241', 'enveloppe.couverture'),
  ('NF DTU 40.25', 'enveloppe.couverture'),
  ('NF DTU 40.29', 'enveloppe.couverture'),
  ('NF DTU 40.35', 'enveloppe.couverture'),
  ('NF DTU 40.36', 'enveloppe.couverture'),
  ('NF DTU 40.37', 'enveloppe.couverture'),
  ('NF DTU 40.41', 'enveloppe.couverture'),
  ('NF DTU 40.44', 'enveloppe.couverture'),
  ('NF DTU 40.45', 'enveloppe.couverture'),
  ('NF DTU 40.46', 'enveloppe.couverture'),
  ('XP DTU 40.5', 'enveloppe.couverture'),
  ('NF DTU 43.1', 'enveloppe.etancheite'),
  ('NF DTU 43.11', 'enveloppe.etancheite'),
  ('NF DTU 43.3', 'enveloppe.etancheite'),
  ('NF DTU 43.4', 'enveloppe.etancheite'),
  ('NF DTU 43.5', 'enveloppe.etancheite'),
  ('NF DTU 43.6', 'enveloppe.etancheite'),
  ('NF DTU 25.1', 'amenagements-interieurs.enduits-et-projections'),
  ('NF DTU 26.1', 'amenagements-interieurs.enduits-et-projections'),
  ('NF DTU 27.1', 'amenagements-interieurs.enduits-et-projections'),
  ('NF DTU 27.2', 'amenagements-interieurs.enduits-et-projections'),
  ('NF DTU 20.13', 'amenagements-interieurs.cloisons-et-doublages'),
  ('NF DTU 25.31', 'amenagements-interieurs.cloisons-et-doublages'),
  ('NF DTU 25.41', 'amenagements-interieurs.cloisons-et-doublages'),
  ('NF DTU 25.42', 'amenagements-interieurs.cloisons-et-doublages'),
  ('NF DTU 35.1', 'amenagements-interieurs.cloisons-et-doublages'),
  ('NF DTU 36.2', 'amenagements-interieurs.menuiseries-interieures'),
  ('NF DTU 36.3', 'amenagements-interieurs.menuiseries-interieures'),
  ('NF DTU 25.231', 'amenagements-interieurs.plafonds'),
  ('NF DTU 25.41', 'amenagements-interieurs.plafonds'),
  ('NF DTU 25.51', 'amenagements-interieurs.plafonds'),
  ('NF DTU 58.1', 'amenagements-interieurs.plafonds'),
  ('NF DTU 58.2', 'amenagements-interieurs.plafonds'),
  ('NF DTU 26.2', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 51.1', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 51.11', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 51.2', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 51.3', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 51.4', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 52.1', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 52.10', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 52.2', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 53.12', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 54.1', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 57.1', 'amenagements-interieurs.revetements-de-sols-chapes-planchers-sureleves'),
  ('NF DTU 59.1', 'amenagements-interieurs.peinture-et-revetements-de-finition'),
  ('NF DTU 59.3', 'amenagements-interieurs.peinture-et-revetements-de-finition'),
  ('NF DTU 59.4', 'amenagements-interieurs.peinture-et-revetements-de-finition'),
  ('NF DTU 59.5', 'amenagements-interieurs.peinture-et-revetements-de-finition'),
  ('XP DTU 40.5', 'equipements-techniques.plomberie-assainissement'),
  ('NF DTU 60.1', 'equipements-techniques.plomberie-assainissement'),
  ('NF DTU 60.11', 'equipements-techniques.plomberie-assainissement'),
  ('NF DTU 60.2', 'equipements-techniques.plomberie-assainissement'),
  ('NF DTU 60.31', 'equipements-techniques.plomberie-assainissement'),
  ('NF DTU 60.32', 'equipements-techniques.plomberie-assainissement'),
  ('NF DTU 60.33', 'equipements-techniques.plomberie-assainissement'),
  ('NF DTU 60.5', 'equipements-techniques.plomberie-assainissement'),
  ('NF DTU 64.1', 'equipements-techniques.plomberie-assainissement'),
  ('NF DTU 61.1', 'equipements-techniques.gaz'),
  ('NF DTU 60.5', 'equipements-techniques.chauffage'),
  ('NF DTU 65.3', 'equipements-techniques.chauffage'),
  ('NF DTU 65.4', 'equipements-techniques.chauffage'),
  ('NF DTU 65.7', 'equipements-techniques.chauffage'),
  ('NF DTU 65.9', 'equipements-techniques.chauffage'),
  ('NF DTU 65.11', 'equipements-techniques.chauffage'),
  ('NF DTU 65.12', 'equipements-techniques.chauffage'),
  ('NF DTU 65.14', 'equipements-techniques.chauffage'),
  ('NF DTU 65.16', 'equipements-techniques.chauffage'),
  ('NF DTU 24.1', 'equipements-techniques.fumisterie'),
  ('NF DTU 24.2', 'equipements-techniques.fumisterie'),
  ('NF DTU 68.3', 'equipements-techniques.ventilation'),
  ('NF DTU 45.1', 'equipements-techniques.isolation-thermique-froid'),
  ('NF DTU 45.2', 'equipements-techniques.isolation-thermique-froid'),
  ('NF DTU 45.10', 'equipements-techniques.isolation-thermique-froid'),
  ('NF DTU 45.11', 'equipements-techniques.isolation-thermique-froid'),
  ('NF DTU 70.1', 'equipements-techniques.installations-electriques')
ON CONFLICT DO NOTHING;

-- NAF rév. 2 (INSEE), section F et activités connexes : 141 codes.
INSERT INTO ref_naf (code, parent_code, niveau, libelle, section) VALUES
  ('16', NULL, 2, 'Travail du bois et fabrication d''articles en bois et en liège, à l’exception des meubles ; fabrication d’articles en vannerie et sparterie', 'C'),
  ('16.2', '16', 3, 'Fabrication d''articles en bois, liège, vannerie et sparterie', 'C'),
  ('16.21', '16.2', 4, 'Fabrication de placage et de panneaux de bois', 'C'),
  ('16.21Z', '16.21', 5, 'Fabrication de placage et de panneaux de bois', 'C'),
  ('16.22', '16.2', 4, 'Fabrication de parquets assemblés', 'C'),
  ('16.22Z', '16.22', 5, 'Fabrication de parquets assemblés', 'C'),
  ('16.23', '16.2', 4, 'Fabrication de charpentes et d''autres menuiseries', 'C'),
  ('16.23Z', '16.23', 5, 'Fabrication de charpentes et d''autres menuiseries', 'C'),
  ('16.24', '16.2', 4, 'Fabrication d''emballages en bois', 'C'),
  ('16.24Z', '16.24', 5, 'Fabrication d''emballages en bois', 'C'),
  ('16.29', '16.2', 4, 'Fabrication d''objets divers en bois ; fabrication d''objets en liège, vannerie et sparterie', 'C'),
  ('16.29Z', '16.29', 5, 'Fabrication d''objets divers en bois ; fabrication d''objets en liège, vannerie et sparterie', 'C'),
  ('23', NULL, 2, 'Fabrication d''autres produits minéraux non métalliques', 'C'),
  ('23.1', '23', 3, 'Fabrication de verre et d''articles en verre', 'C'),
  ('23.11', '23.1', 4, 'Fabrication de verre plat', 'C'),
  ('23.11Z', '23.11', 5, 'Fabrication de verre plat', 'C'),
  ('23.12', '23.1', 4, 'Façonnage et transformation du verre plat', 'C'),
  ('23.12Z', '23.12', 5, 'Façonnage et transformation du verre plat', 'C'),
  ('23.13', '23.1', 4, 'Fabrication de verre creux', 'C'),
  ('23.13Z', '23.13', 5, 'Fabrication de verre creux', 'C'),
  ('23.14', '23.1', 4, 'Fabrication de fibres de verre', 'C'),
  ('23.14Z', '23.14', 5, 'Fabrication de fibres de verre', 'C'),
  ('23.19', '23.1', 4, 'Fabrication et façonnage d''autres articles en verre, y compris verre technique', 'C'),
  ('23.19Z', '23.19', 5, 'Fabrication et façonnage d''autres articles en verre, y compris verre technique', 'C'),
  ('23.2', '23', 3, 'Fabrication de produits réfractaires', 'C'),
  ('23.20', '23.2', 4, 'Fabrication de produits réfractaires', 'C'),
  ('23.20Z', '23.20', 5, 'Fabrication de produits réfractaires', 'C'),
  ('23.3', '23', 3, 'Fabrication de matériaux de construction en terre cuite', 'C'),
  ('23.31', '23.3', 4, 'Fabrication de carreaux en céramique', 'C'),
  ('23.31Z', '23.31', 5, 'Fabrication de carreaux en céramique', 'C'),
  ('23.32', '23.3', 4, 'Fabrication de briques, tuiles et produits de construction, en terre cuite', 'C'),
  ('23.32Z', '23.32', 5, 'Fabrication de briques, tuiles et produits de construction, en terre cuite', 'C'),
  ('23.5', '23', 3, 'Fabrication de ciment, chaux et plâtre', 'C'),
  ('23.51', '23.5', 4, 'Fabrication de ciment', 'C'),
  ('23.51Z', '23.51', 5, 'Fabrication de ciment', 'C'),
  ('23.52', '23.5', 4, 'Fabrication de chaux et plâtre', 'C'),
  ('23.52Z', '23.52', 5, 'Fabrication de chaux et plâtre', 'C'),
  ('23.6', '23', 3, 'Fabrication d''ouvrages en béton, en ciment ou en plâtre', 'C'),
  ('23.61', '23.6', 4, 'Fabrication d''éléments en béton pour la construction', 'C'),
  ('23.61Z', '23.61', 5, 'Fabrication d''éléments en béton pour la construction', 'C'),
  ('23.62', '23.6', 4, 'Fabrication d''éléments en plâtre pour la construction', 'C'),
  ('23.62Z', '23.62', 5, 'Fabrication d''éléments en plâtre pour la construction', 'C'),
  ('23.63', '23.6', 4, 'Fabrication de béton prêt à l''emploi', 'C'),
  ('23.63Z', '23.63', 5, 'Fabrication de béton prêt à l''emploi', 'C'),
  ('23.64', '23.6', 4, 'Fabrication de mortiers et bétons secs', 'C'),
  ('23.64Z', '23.64', 5, 'Fabrication de mortiers et bétons secs', 'C'),
  ('23.65', '23.6', 4, 'Fabrication d''ouvrages en fibre-ciment', 'C'),
  ('23.65Z', '23.65', 5, 'Fabrication d''ouvrages en fibre-ciment', 'C'),
  ('23.69', '23.6', 4, 'Fabrication d''autres ouvrages en béton, en ciment ou en plâtre', 'C'),
  ('23.69Z', '23.69', 5, 'Fabrication d''autres ouvrages en béton, en ciment ou en plâtre', 'C'),
  ('23.7', '23', 3, 'Taille, façonnage et finissage de pierres', 'C'),
  ('23.70', '23.7', 4, 'Taille, façonnage et finissage de pierres', 'C'),
  ('23.70Z', '23.70', 5, 'Taille, façonnage et finissage de pierres', 'C'),
  ('25', NULL, 2, 'Fabrication de produits métalliques, à l’exception des machines et des équipements', 'C'),
  ('25.1', '25', 3, 'Fabrication d''éléments en métal pour la construction', 'C'),
  ('25.11', '25.1', 4, 'Fabrication de structures métalliques et de parties de structures', 'C'),
  ('25.11Z', '25.11', 5, 'Fabrication de structures métalliques et de parties de structures', 'C'),
  ('25.12', '25.1', 4, 'Fabrication de portes et fenêtres en métal', 'C'),
  ('25.12Z', '25.12', 5, 'Fabrication de portes et fenêtres en métal', 'C'),
  ('41', NULL, 2, 'Construction de bâtiments', 'F'),
  ('41.1', '41', 3, 'Promotion immobilière', 'F'),
  ('41.10', '41.1', 4, 'Promotion immobilière', 'F'),
  ('41.10A', '41.10', 5, 'Promotion immobilière de logements', 'F'),
  ('41.10B', '41.10', 5, 'Promotion immobilière de bureaux', 'F'),
  ('41.10C', '41.10', 5, 'Promotion immobilière d''autres bâtiments', 'F'),
  ('41.10D', '41.10', 5, 'Supports juridiques de programmes', 'F'),
  ('41.2', '41', 3, 'Construction de bâtiments résidentiels et non résidentiels', 'F'),
  ('41.20', '41.2', 4, 'Construction de bâtiments résidentiels et non résidentiels', 'F'),
  ('41.20A', '41.20', 5, 'Construction de maisons individuelles', 'F'),
  ('41.20B', '41.20', 5, 'Construction d''autres bâtiments', 'F'),
  ('42', NULL, 2, 'Génie civil', 'F'),
  ('42.1', '42', 3, 'Construction de routes et de voies ferrées', 'F'),
  ('42.11', '42.1', 4, 'Construction de routes et autoroutes', 'F'),
  ('42.11Z', '42.11', 5, 'Construction de routes et autoroutes', 'F'),
  ('42.12', '42.1', 4, 'Construction de voies ferrées de surface et souterraines', 'F'),
  ('42.12Z', '42.12', 5, 'Construction de voies ferrées de surface et souterraines', 'F'),
  ('42.13', '42.1', 4, 'Construction de ponts et tunnels', 'F'),
  ('42.13A', '42.13', 5, 'Construction d''ouvrages d''art', 'F'),
  ('42.13B', '42.13', 5, 'Construction et entretien de tunnels', 'F'),
  ('42.2', '42', 3, 'Construction de réseaux et de lignes', 'F'),
  ('42.21', '42.2', 4, 'Construction de réseaux pour fluides', 'F'),
  ('42.21Z', '42.21', 5, 'Construction de réseaux pour fluides', 'F'),
  ('42.22', '42.2', 4, 'Construction de réseaux électriques et de télécommunications', 'F'),
  ('42.22Z', '42.22', 5, 'Construction de réseaux électriques et de télécommunications', 'F'),
  ('42.9', '42', 3, 'Construction d''autres ouvrages de génie civil', 'F'),
  ('42.91', '42.9', 4, 'Construction d''ouvrages maritimes et fluviaux', 'F'),
  ('42.91Z', '42.91', 5, 'Construction d''ouvrages maritimes et fluviaux', 'F'),
  ('42.99', '42.9', 4, 'Construction d''autres ouvrages de génie civil n.c.a.', 'F'),
  ('42.99Z', '42.99', 5, 'Construction d''autres ouvrages de génie civil n.c.a.', 'F'),
  ('43', NULL, 2, 'Travaux de construction spécialisés', 'F'),
  ('43.1', '43', 3, 'Démolition et préparation des sites', 'F'),
  ('43.11', '43.1', 4, 'Travaux de démolition', 'F'),
  ('43.11Z', '43.11', 5, 'Travaux de démolition', 'F'),
  ('43.12', '43.1', 4, 'Travaux de préparation des sites', 'F'),
  ('43.12A', '43.12', 5, 'Travaux de terrassement courants et travaux préparatoires', 'F'),
  ('43.12B', '43.12', 5, 'Travaux de terrassement spécialisés ou de grande masse', 'F'),
  ('43.13', '43.1', 4, 'Forages et sondages', 'F'),
  ('43.13Z', '43.13', 5, 'Forages et sondages', 'F'),
  ('43.2', '43', 3, 'Travaux d''installation électrique, plomberie et autres travaux d''installation', 'F'),
  ('43.21', '43.2', 4, 'Installation électrique', 'F'),
  ('43.21A', '43.21', 5, 'Travaux d''installation électrique dans tous locaux', 'F'),
  ('43.21B', '43.21', 5, 'Travaux d''installation électrique sur la voie publique', 'F'),
  ('43.22', '43.2', 4, 'Travaux de plomberie et installation de chauffage et de conditionnement d''air', 'F'),
  ('43.22A', '43.22', 5, 'Travaux d''installation d''eau et de gaz en tous locaux', 'F'),
  ('43.22B', '43.22', 5, 'Travaux d''installation d''équipements thermiques et de climatisation', 'F'),
  ('43.29', '43.2', 4, 'Autres travaux d''installation', 'F'),
  ('43.29A', '43.29', 5, 'Travaux d''isolation', 'F'),
  ('43.29B', '43.29', 5, 'Autres travaux d''installation n.c.a.', 'F'),
  ('43.3', '43', 3, 'Travaux de finition', 'F'),
  ('43.31', '43.3', 4, 'Travaux de plâtrerie', 'F'),
  ('43.31Z', '43.31', 5, 'Travaux de plâtrerie', 'F'),
  ('43.32', '43.3', 4, 'Travaux de menuiserie', 'F'),
  ('43.32A', '43.32', 5, 'Travaux de menuiserie bois et PVC', 'F'),
  ('43.32B', '43.32', 5, 'Travaux de menuiserie métallique et serrurerie', 'F'),
  ('43.32C', '43.32', 5, 'Agencement de lieux de vente', 'F'),
  ('43.33', '43.3', 4, 'Travaux de revêtement des sols et des murs', 'F'),
  ('43.33Z', '43.33', 5, 'Travaux de revêtement des sols et des murs', 'F'),
  ('43.34', '43.3', 4, 'Travaux de peinture et vitrerie', 'F'),
  ('43.34Z', '43.34', 5, 'Travaux de peinture et vitrerie', 'F'),
  ('43.39', '43.3', 4, 'Autres travaux de finition', 'F'),
  ('43.39Z', '43.39', 5, 'Autres travaux de finition', 'F'),
  ('43.9', '43', 3, 'Autres travaux de construction spécialisés', 'F'),
  ('43.91', '43.9', 4, 'Travaux de couverture', 'F'),
  ('43.91A', '43.91', 5, 'Travaux de charpente', 'F'),
  ('43.91B', '43.91', 5, 'Travaux de couverture par éléments', 'F'),
  ('43.99', '43.9', 4, 'Autres travaux de construction spécialisés n.c.a.', 'F'),
  ('43.99A', '43.99', 5, 'Travaux d''étanchéification', 'F'),
  ('43.99B', '43.99', 5, 'Travaux de montage de structures métalliques', 'F'),
  ('43.99C', '43.99', 5, 'Travaux de maçonnerie générale et gros œuvre de bâtiment', 'F'),
  ('43.99D', '43.99', 5, 'Autres travaux spécialisés de construction', 'F'),
  ('43.99E', '43.99', 5, 'Location avec opérateur de matériel de construction', 'F'),
  ('71', NULL, 2, 'Activités d''architecture et d''ingénierie ; activités de contrôle et analyses techniques', 'M'),
  ('71.1', '71', 3, 'Activités d''architecture et d''ingénierie', 'M'),
  ('71.11', '71.1', 4, 'Activités d''architecture', 'M'),
  ('71.11Z', '71.11', 5, 'Activités d''architecture', 'M'),
  ('71.12', '71.1', 4, 'Activités d''ingénierie', 'M'),
  ('71.12A', '71.12', 5, 'Activité des géomètres', 'M'),
  ('71.12B', '71.12', 5, 'Ingénierie, études techniques', 'M'),
  ('71.2', '71', 3, 'Activités de contrôle et analyses techniques', 'M'),
  ('71.20', '71.2', 4, 'Activités de contrôle et analyses techniques', 'M'),
  ('71.20B', '71.20', 5, 'Analyses, essais et inspections techniques', 'M')
ON CONFLICT (code) DO UPDATE SET parent_code = EXCLUDED.parent_code, niveau = EXCLUDED.niveau, libelle = EXCLUDED.libelle, section = EXCLUDED.section;
